// Client for the "AI" (natural-language → session) Worker, plus the rule for deciding whether
// a `?loadFromURL=` session came from it.
//
// The Worker builds a session from a prompt and hands back a link. It also holds the default
// model's API key as a server-side secret — this app NEVER holds one. Anything shipped to the
// browser is public, so a key here would be readable from the bundle in seconds. Users may
// still bring their own key (Advanced tab); it's passed through for that one request.

/**
 * Where the AI service lives when nothing says otherwise.
 *
 * Hardcoded because the alternative silently removed the feature. This URL only ever reached
 * the browser via `VITE_ANCIR_NL_URL` in `.env` — and `.env` is gitignored, so Cloudflare cloned
 * the repo, built with the var undefined, and `NL_CONFIGURED` came out false: the AI button
 * vanished from production with no build error and no console line. It looked like a missing
 * icon. Nothing is leaked by putting it here; a public URL is inlined into the bundle either
 * way (the API key is a Worker-side secret and never comes near this file).
 */
const DEFAULT_NL_URL = 'https://ancir-nl.david-cumin.workers.dev';

/**
 * Resolve the service URL from whatever the build was given.
 *
 * A separate, exported function purely so it can be TESTED: a test run loads `.env`, so
 * `import.meta.env.VITE_ANCIR_NL_URL` is always set locally and the unset case — the one that
 * broke production — is unreachable from a test that reads the environment.
 *
 * @param {string|undefined} configured the raw VITE_ANCIR_NL_URL
 * @returns {string} the origin, with any trailing slash removed
 */
export function resolveNlUrl(configured) {
	// `undefined` = "not configured" ⇒ take the default. An EXPLICIT empty string is different:
	// it means "turn this off", which a fork or a privacy-conscious deployment may well want.
	return (configured ?? DEFAULT_NL_URL).replace(/\/+$/, '');
}

const configuredNlUrl = import.meta.env?.VITE_ANCIR_NL_URL;

/** Origin of the NL Worker, e.g. https://ancir-nl.david-cumin.workers.dev — not a secret. */
export const NL_URL = resolveNlUrl(configuredNlUrl);

/** True when the AI feature is configured at all (otherwise the button never shows). */
export const NL_CONFIGURED = NL_URL.length > 0;

// Say which service we're talking to, so "why is the AI button missing, or pointing somewhere
// odd?" is one console line rather than an afternoon. The disabled case is warned about in
// every build — it removes a visible feature, so it should never be silent. The override is
// only noted in dev, where it's a normal thing to be doing (a local `wrangler dev`).
if (typeof console !== 'undefined') {
	if (!NL_CONFIGURED) {
		console.warn(
			'[AnCiR] AI features are OFF: VITE_ANCIR_NL_URL is set to an empty value. ' +
				'Unset it to use the default service, or point it at your own.'
		);
	} else if (import.meta.env?.DEV && NL_URL !== DEFAULT_NL_URL) {
		// Only when it's genuinely pointing elsewhere (a local `wrangler dev`, say) — a .env that
		// merely restates the default shouldn't chatter on every reload.
		console.info(`[AnCiR] AI service overridden by VITE_ANCIR_NL_URL → ${NL_URL}`);
	}
}

// Sessions from THIS host were generated by us, so we may re-tidy their layout and warn that
// they're AI-generated. Anything else — a user's own session URL — is left exactly as saved.
const TRUSTED_HOST_SUFFIX = '.david-cumin.workers.dev';

/**
 * Was this session URL produced by our Worker?
 *
 * Compares the parsed HOSTNAME rather than searching the string: `url.includes(host)` would
 * also match `https://evil.example/?x=david-cumin.workers.dev`, letting any page pass itself
 * off as ours. A relative/other URL simply isn't trusted.
 *
 * @param {string} url
 * @returns {boolean}
 */
export function isTrustedSessionUrl(url) {
	try {
		const base = typeof window !== 'undefined' ? window.location.href : undefined;
		const host = new URL(url, base).hostname.toLowerCase();
		if (NL_CONFIGURED && host === new URL(NL_URL).hostname.toLowerCase()) return true;
		return host.endsWith(TRUSTED_HOST_SUFFIX);
	} catch {
		return false; // unparseable ⇒ not ours
	}
}

/**
 * Is the Worker reachable? Used to decide whether to offer the AI button at all — a plain
 * `navigator.onLine` only says a network exists, not that our Worker is up.
 * @returns {Promise<boolean>}
 */
export async function checkNlHealth({ timeoutMs = 4000 } = {}) {
	if (!NL_CONFIGURED) return false;
	try {
		const res = await fetch(`${NL_URL}/health`, { signal: AbortSignal.timeout(timeoutMs) });
		if (!res.ok) return false;
		return (await res.json())?.ok === true;
	} catch {
		return false; // offline, blocked, down, or too slow — just don't offer the button
	}
}

/**
 * POST to the Worker and turn every failure into a message a person can act on. Shared by the
 * build and edit paths — same service, same ways of going wrong.
 *
 * @throws {Error} with a human-readable message — callers must surface it, never swallow it.
 */
async function postNl(path, payload, { timeoutMs = 90000 } = {}) {
	if (!NL_CONFIGURED) throw new Error('The AI service is not configured for this build.');

	let res;
	try {
		res = await fetch(`${NL_URL}${path}`, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify(payload),
			signal: AbortSignal.timeout(timeoutMs)
		});
	} catch (e) {
		throw new Error(
			e?.name === 'TimeoutError'
				? 'The AI service took too long to respond. Try again, or simplify the request.'
				: `Could not reach the AI service. ${e?.message ?? e}`
		);
	}

	// Not every failure is JSON: a rate-limit or block can be handled at Cloudflare's edge and
	// come back as HTML, so parse defensively rather than turning it into "unreadable".
	let body = null;
	try {
		body = await res.json();
	} catch {
		/* fall through to the status-based messages below */
	}

	if (!res.ok) {
		if (res.status === 429) {
			// Two different limits arrive as 429: our own per-IP throttle, and the model's
			// rate/usage cap. The Worker names which one, so prefer its message (with the
			// provider's detail, e.g. "Limit 14400, Used 14400, try again in 2m") over a
			// generic one; only invent text if it sent none.
			const retry = Number(body?.retryAfterS ?? res.headers.get('Retry-After')) || 60;
			const msg =
				body?.error ??
				`Too many requests. Wait about ${retry}s and try again.`;
			throw new Error([msg, body?.detail].filter(Boolean).join('\n'));
		}
		if (!body) {
			throw new Error(
				`The AI service returned an error (HTTP ${res.status}) that couldn't be read.`
			);
		}
		// The Worker's own message is the useful one (bad key, unusable draft…).
		const detail = body?.detail?.error?.message ?? body?.detail?.message;
		throw new Error(
			[body?.error ?? `HTTP ${res.status}`, detail, ...(body?.errors ?? [])]
				.filter(Boolean)
				.join('\n')
		);
	}
	if (!body) throw new Error('The AI service returned an unreadable response.');
	return body;
}

/**
 * Build a NEW session from a prompt. Sends `llm` only when the user supplied their own;
 * otherwise the Worker uses its configured default.
 *
 * @param {{prompt:string, llm?:{baseUrl?:string, apiKey?:string, model?:string}}} req
 * @returns {Promise<{url:string, sessionUrl:string, sessionId:string, warnings:string[], errors:string[]}>}
 */
export function buildNlSession({ prompt, llm } = {}, opts = {}) {
	return postNl('/build', { prompt, ...(llm ? { llm } : {}) }, opts);
}

/**
 * Ask for changes to the session the user already has open.
 *
 * Returns a SPEC, not a session: the Worker has never seen this session and can't mutate it.
 * `session` is the structure summary (see utils/aiEdit.js summariseSession) — never the data.
 * The caller compiles and validates the spec locally before anything is applied.
 *
 * @param {{prompt:string, session:object, llm?:object}} req
 * @returns {Promise<{analyses:any[], plots:any[], changes:any[]}>}
 */
export function editNlSession({ prompt, session, llm } = {}, opts = {}) {
	return postNl('/edit', { prompt, session, ...(llm ? { llm } : {}) }, opts);
}
