import { describe, expect, it } from 'vitest';
import { isTrustedSessionUrl, NL_URL, resolveNlUrl } from './nlSession.js';

// The AI button is gated on NL_CONFIGURED, which came from VITE_ANCIR_NL_URL in .env — and
// .env is gitignored. So Cloudflare built with it undefined, NL_CONFIGURED came out false, and
// the button silently vanished from production: no build error, no console line, and it
// presented as "the AI icon doesn't show".
//
// Tested through resolveNlUrl rather than the env: a test run LOADS .env, so the unset case —
// the only one that breaks — can't be reached by reading import.meta.env here. That's the same
// blind spot that let this reach production in the first place.
describe('resolveNlUrl', () => {
	it('falls back to a default when unset — the Cloudflare/clean-clone case', () => {
		expect(resolveNlUrl(undefined)).toMatch(/^https:\/\/.+/);
		expect(resolveNlUrl(undefined).length).toBeGreaterThan(0); // ⇒ NL_CONFIGURED true
	});

	it('honours an override, and trims a trailing slash so `${NL_URL}/build` is well formed', () => {
		expect(resolveNlUrl('http://localhost:8799')).toBe('http://localhost:8799');
		expect(resolveNlUrl('http://localhost:8799/')).toBe('http://localhost:8799');
		expect(resolveNlUrl('https://x.example//')).toBe('https://x.example');
		expect(NL_URL.endsWith('/')).toBe(false);
	});

	it('treats an EXPLICIT empty value as "turn the AI off"', () => {
		// Distinct from unset: a fork should be able to disable the feature deliberately.
		expect(resolveNlUrl('')).toBe('');
	});

	it('defaults to a host the trust rule then accepts — the two must not disagree', () => {
		// A default that isTrustedSessionUrl rejected would load AI sessions with no tidy and no
		// "generated by AI" warning.
		expect(isTrustedSessionUrl(`${resolveNlUrl(undefined)}/sessions/abc`)).toBe(true);
	});
});

// Only sessions our own Worker built get re-tidied + the AI warning. Everything else — above
// all a user's own session URL — must be left exactly as they saved it.
describe('isTrustedSessionUrl', () => {
	it('trusts our Worker host', () => {
		expect(isTrustedSessionUrl('https://ancir-nl.david-cumin.workers.dev/sessions/abc')).toBe(true);
		expect(isTrustedSessionUrl('https://anything.david-cumin.workers.dev/sessions/x')).toBe(true);
	});

	it('does NOT trust a URL that merely CONTAINS the host string', () => {
		// The whole reason for parsing the hostname instead of `url.includes(host)`: otherwise
		// any site could pass itself off as ours and have its layout silently rewritten.
		expect(isTrustedSessionUrl('https://evil.example/?x=ancir-nl.david-cumin.workers.dev')).toBe(
			false
		);
		expect(isTrustedSessionUrl('https://david-cumin.workers.dev.evil.example/s')).toBe(false);
		expect(isTrustedSessionUrl('https://notdavid-cumin.workers.dev/s')).toBe(false);
	});

	it("does not trust someone else's host, a relative URL, or junk", () => {
		expect(isTrustedSessionUrl('https://example.com/my-session.json')).toBe(false);
		expect(isTrustedSessionUrl('https://other.workers.dev/sessions/x')).toBe(false);
		expect(isTrustedSessionUrl('/static/sessions/demos/demo-tp-cosinor.json')).toBe(false);
		expect(isTrustedSessionUrl('')).toBe(false);
		expect(isTrustedSessionUrl('not a url')).toBe(false);
		expect(isTrustedSessionUrl(undefined)).toBe(false);
	});

	it('is case-insensitive about the host', () => {
		expect(isTrustedSessionUrl('https://ANCIR-NL.David-Cumin.Workers.Dev/sessions/a')).toBe(true);
	});
});
