// pythonExport.js
//
// Client-side port of `tools/ancir_to_python.py`'s `emit()`. Given a session
// object (the same shape `outputCoreAsJson()` produces) and the source text of
// `tools/ancir_runtime.py`, it assembles a single, self-contained Python script
// that reproduces the session's analyses (columns.csv, table processes, plots).
//
// The heavy analysis code (ancir_runtime.py) is the single source of truth and
// is passed in verbatim by the caller (lazily `?raw`-imported). Only the small
// HEADER / FOOTER_RUN wrappers are duplicated here.
//
// KEEP IN SYNC with tools/ancir_to_python.py (HEADER, FOOTER_RUN, the import
// stripping, the column-metadata shape, and the data-embedding lines). If the
// CLI's wrappers change, mirror them here.

// Mirrors HEADER in ancir_to_python.py (docstring reworded — this copy is
// generated in-app rather than by the CLI).
const HEADER = `#!/usr/bin/env python3
"""Generated by AnCiR — export session as Python (experimental). Do not edit by hand.

Reproduces the analyses in an AnCiR session. Requires: numpy, pandas, scipy.
Run it (\`python this_file.py\`) to write <name>_output/ with columns.csv,
columns_after_tables.csv, and any plots.
"""
from __future__ import annotations
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import optimize as sp_optimize, stats as sp_stats
`;

// Mirrors FOOTER_RUN in ancir_to_python.py. Note: `\\n` below is a literal
// backslash-n in the emitted script (a Python newline escape), matching the
// CLI's `"\\n"` inside its triple-quoted constant.
const FOOTER_RUN = `

# ----------------------------------------------------------------------
# Pipeline
# ----------------------------------------------------------------------

def main():
    columns_index = {}
    for cid, meta in COLUMN_META.items():
        col = Column(
            id=cid,
            name=meta["name"],
            type=meta["type"],
            data=meta.get("data"),
            raw_data=RAW_DATA,
            time_format=meta.get("timeFormat"),
            bin_width=meta.get("binWidth", 1.0),
            compression=meta.get("compression"),
            ref_id=meta.get("refId"),
            group_label=meta.get("groupLabel"),
            columns_index=None,  # set after all are built
            processes=meta.get("processes", []),
        )
        columns_index[cid] = col
    # link cross-column references
    for c in columns_index.values():
        c.columns_index = columns_index

    stored = dict(STORED_VALUES)

    output_dir = Path(__file__).with_suffix("").name + "_output"
    out_path = Path(output_dir)
    out_path.mkdir(exist_ok=True)

    # Save column outputs (after processes applied)
    rows = {}
    for c in columns_index.values():
        rows[c.name] = c.get_data()
    # pad to equal length for DataFrame
    max_len = max((len(v) for v in rows.values()), default=0)
    for k in rows:
        rows[k] = list(rows[k]) + [None] * (max_len - len(rows[k]))
    df_cols = pd.DataFrame(rows)
    df_cols.to_csv(out_path / "columns.csv", index=False)
    print(f"[ancir] wrote {out_path / 'columns.csv'} ({len(df_cols)} rows, {len(df_cols.columns)} cols)")

    # Run table processes: each writes into RAW_DATA[out_id], so column data is
    # updated in-place. After running, dump every column to CSV. Free table-
    # process nodes are stored in creation order (oldest first), which respects
    # dependencies, so they run in array order.
    #
    # By default the runtime is strict (STRICT_PROCESSES = True): an unknown
    # process raises UnsupportedProcessError and aborts here rather than
    # silently producing wrong output. Set STRICT_PROCESSES = False above to
    # continue past unknown processes (output WILL be wrong); they are then
    # listed in the summary below.
    for tp in TABLE_PROCESSES:
        ok = run_table_process(tp["name"], tp["args"],
                               columns_index, RAW_DATA, stored)
        print(f"[ancir]   {tp['name']}: {'ok' if ok else 'skipped/empty'}")

    # Dump all columns again (now reflecting TP outputs)
    rows = {}
    for c in columns_index.values():
        rows[c.name] = c.get_data()
    max_len = max((len(v) for v in rows.values()), default=0)
    for k in rows:
        rows[k] = list(rows[k]) + [None] * (max_len - len(rows[k]))
    df_final = pd.DataFrame(rows)
    df_final.to_csv(out_path / "columns_after_tables.csv", index=False)
    print(f"[ancir] wrote {out_path / 'columns_after_tables.csv'} "
          f"({len(df_final)} rows, {len(df_final.columns)} cols)")

    # Render plots
    if PLOTS:
        render_plots(PLOTS, columns_index, out_path)

    # Loud summary of any unsupported processes (only reachable when
    # STRICT_PROCESSES was set to False; strict mode aborts earlier).
    if UNSUPPORTED_PROCESSES:
        print("\\n" + "=" * 70)
        print("WARNING: the following processes are NOT implemented by the "
              "runtime.\\nTheir outputs are WRONG (the processes were skipped):")
        for kind, name in UNSUPPORTED_PROCESSES:
            print(f"  - [{kind}] {name}")
        print("=" * 70)


if __name__ == "__main__":
    main()
`;

/**
 * Strip the runtime's own numpy/pandas/scipy/`from __future__` imports — HEADER
 * re-declares them. Mirrors the loop in ancir_to_python.py:emit().
 * @param {string} runtimeSrc
 * @returns {string}
 */
function stripRuntimeImports(runtimeSrc) {
	const kept = [];
	for (const line of runtimeSrc.split('\n')) {
		if (
			line.startsWith('from __future__') ||
			line.startsWith('import ') ||
			line.startsWith('from ')
		) {
			if (
				line.includes('numpy') ||
				line.includes('pandas') ||
				line.includes('scipy') ||
				line.startsWith('from __future__')
			) {
				continue;
			}
		}
		kept.push(line);
	}
	return kept.join('\n');
}

/**
 * Pluck the JSON-serialisable metadata for a column. Mirrors
 * ancir_to_python.py:_col_meta_for_column — keys whose value is null are
 * dropped (except `processes`, which is always kept).
 * @param {any} col
 */
function colMetaForColumn(col) {
	const meta = {
		name: col.name ?? null,
		type: col.type ?? 'number',
		data: col.data ?? null,
		compression: col.compression ?? null,
		timeFormat: col.timeFormat ?? null,
		binWidth: col.binWidth ?? 1.0,
		refId: col.refId ?? null,
		groupLabel: col.groupLabel ?? null,
		processes: (col.processes ?? []).map((p) => ({
			funcname: p.funcname ?? null,
			name: p.name ?? null,
			args: p.args ?? {}
		}))
	};
	const out = {};
	for (const [k, v] of Object.entries(meta)) {
		if (v !== null || k === 'processes') out[k] = v;
	}
	return out;
}

// Embed a value the way the CLI does: `json.loads("<escaped json text>")`.
// JSON.stringify of the JSON text yields a string literal valid in both JSON
// and Python, mirroring the CLI's json.dumps(json.dumps(x)).
function embed(name, value) {
	return `${name} = json.loads(${JSON.stringify(JSON.stringify(value))})`;
}

/**
 * Nodes whose output is BAKED rather than re-run.
 *
 * Random and SimulatedData draw from the JS engine's seeded PRNG. Re-running them in another
 * language cannot reproduce that draw, so the exported script used to OVERWRITE the session's
 * real values with fresh ones — silently, on every run, with no warning. Measured on
 * demo-tp-random: the session holds 9.23, 3.33, 1.98, 9.49; two Python runs gave
 * 6.54/8.67/0.06/4.43 and 7.86/4.87/2.24/0.69.
 *
 * The session already carries what they produced — `rawData` holds each generated column
 * under its output id, which is how the app redraws it on load. So the fix is simply not to
 * run them again: the embedded data IS the result, and the script reproduces the session
 * exactly.
 *
 * `simulatedata` (one d) is the DISPLAY name "Simulate Data" with its space removed. Sessions
 * normally store the registry key, but the Python runtime keeps a display-name map because
 * some store the label instead — so both spellings are listed rather than assumed.
 *
 * Deterministic sources (SequenceColumn, BlankColumn) are NOT here. They re-run identically,
 * and leaving them in keeps the script showing how the column was built.
 *
 * Kept in sync with the R exporter by a test — neither file may import the other, because
 * both are inlined verbatim into their sidecars.
 */
const BAKED_NODES = ['random', 'simulateddata', 'simulatedata'];

/** Node name as stored ("Simulate Data", "SimulatedData") to its runtime key. */
function nodeKey(name) {
	return String(name ?? '')
		.toLowerCase()
		.replace(/\s+/g, '');
}

/**
 * Build a self-contained Python script reproducing `session`.
 * @param {any} session - parsed session object (as from outputCoreAsJson()).
 * @param {string} runtimeSrc - verbatim source of tools/ancir_runtime.py.
 * @returns {string} the Python script text.
 */
export function sessionToPython(session, runtimeSrc) {
	if (!session || typeof session !== 'object') {
		throw new Error('sessionToPython: invalid session object');
	}
	if (typeof runtimeSrc !== 'string' || !runtimeSrc) {
		throw new Error('sessionToPython: missing runtime source');
	}

	const runtimeBlock = stripRuntimeImports(runtimeSrc);

	const rawData = session.rawData ?? {};
	const columns = session.data ?? [];
	// Analyses are free table-process nodes; legacy grouped `tables` are flattened
	// in for back-compat (mirrors the CLI).
	const tableProcesses = session.tableProcesses ?? [];
	const legacyTables = session.tables ?? [];
	const plots = session.plots ?? [];
	const storedValues = session.storedValues ?? {};

	/** @type {Record<number, any>} */
	const colMeta = {};
	for (const c of columns) {
		if (c?.id == null) continue;
		colMeta[c.id] = colMetaForColumn(c);
	}

	const tpsClean = [];
	for (const tp of tableProcesses) {
		if (BAKED_NODES.includes(nodeKey(tp.name))) continue;
		tpsClean.push({ name: tp.name ?? null, args: tp.args ?? {} });
	}
	for (const t of legacyTables) {
		for (const p of t.processes ?? []) {
			if (BAKED_NODES.includes(nodeKey(p.name))) continue;
			tpsClean.push({ name: p.name ?? null, args: p.args ?? {} });
		}
	}

	const parts = [HEADER, '', runtimeBlock, ''];
	parts.push('# ----- Session data (embedded) -----');
	parts.push(embed('RAW_DATA', rawData));
	parts.push(
		"RAW_DATA = {int(k) if k.lstrip('-').isdigit() else k: v for k, v in RAW_DATA.items()}"
	);
	parts.push(embed('_COL_META_RAW', colMeta));
	parts.push('COLUMN_META = {int(k): v for k, v in _COL_META_RAW.items()}');
	parts.push(embed('TABLE_PROCESSES', tpsClean));
	parts.push(embed('PLOTS', plots));
	parts.push(embed('STORED_VALUES', storedValues));
	parts.push(FOOTER_RUN);

	return parts.join('\n');
}
