// pythonExport.js
//
// Client-side port of `tools/ancir_to_python.py`'s `emit()`. Given a session
// object (the same shape `outputCoreAsJson()` produces) and the source text of
// `tools/ancir_runtime.py`, it assembles a single, self-contained Python script
// that reproduces the session's analyses (columns.csv, table processes, plots).
//
// The heavy analysis code (ancir_runtime.py) is the single source of truth and
// is passed in verbatim by the caller (lazily `?raw`-imported). Only the small
// HEADER / FOOTER_RUN wrappers are duplicated here.
//
// KEEP IN SYNC with tools/ancir_to_python.py (HEADER, FOOTER_RUN, the import
// stripping, the column-metadata shape, and the data-embedding lines). If the
// CLI's wrappers change, mirror them here.

// Mirrors HEADER in ancir_to_python.py (docstring reworded — this copy is
// generated in-app rather than by the CLI).
const HEADER = `#!/usr/bin/env python3
"""Generated by AnCiR — export session as Python (experimental). Do not edit by hand.

Reproduces the analyses in an AnCiR session. Requires: numpy, pandas, scipy.
Run it (\`python this_file.py\`) to write <name>_output/ with columns.csv,
columns_after_tables.csv, and any plots.
"""
from __future__ import annotations
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import optimize as sp_optimize, stats as sp_stats
`;

// Mirrors FOOTER_RUN in ancir_to_python.py. Note: `\\n` below is a literal
// backslash-n in the emitted script (a Python newline escape), matching the
// CLI's `"\\n"` inside its triple-quoted constant.
const FOOTER_RUN = `

# ----------------------------------------------------------------------
# Pipeline
# ----------------------------------------------------------------------

def main():
    columns_index = {}
    for cid, meta in COLUMN_META.items():
        col = Column(
            id=cid,
            name=meta["name"],
            type=meta["type"],
            data=meta.get("data"),
            raw_data=RAW_DATA,
            time_format=meta.get("timeFormat"),
            bin_width=meta.get("binWidth", 1.0),
            compression=meta.get("compression"),
            ref_id=meta.get("refId"),
            group_label=meta.get("groupLabel"),
            columns_index=None,  # set after all are built
            processes=meta.get("processes", []),
        )
        columns_index[cid] = col
    # link cross-column references
    for c in columns_index.values():
        c.columns_index = columns_index

    stored = dict(STORED_VALUES)

    output_dir = Path(__file__).with_suffix("").name + "_output"
    out_path = Path(output_dir)
    out_path.mkdir(exist_ok=True)

    # Save column outputs (after processes applied)
    rows = {}
    for c in columns_index.values():
        rows[c.name] = c.get_data()
    # pad to equal length for DataFrame
    max_len = max((len(v) for v in rows.values()), default=0)
    for k in rows:
        rows[k] = list(rows[k]) + [None] * (max_len - len(rows[k]))
    df_cols = pd.DataFrame(rows)
    df_cols.to_csv(out_path / "columns.csv", index=False)
    print(f"[ancir] wrote {out_path / 'columns.csv'} ({len(df_cols)} rows, {len(df_cols.columns)} cols)")

    # Run table processes: each writes into RAW_DATA[out_id], so column data is
    # updated in-place. After running, dump every column to CSV. Free table-
    # process nodes are stored in creation order (oldest first), which respects
    # dependencies, so they run in array order.
    #
    # By default the runtime is strict (STRICT_PROCESSES = True): an unknown
    # process raises UnsupportedProcessError and aborts here rather than
    # silently producing wrong output. Set STRICT_PROCESSES = False above to
    # continue past unknown processes (output WILL be wrong); they are then
    # listed in the summary below.
    for tp in TABLE_PROCESSES:
        ok = run_table_process(tp["name"], tp["args"],
                               columns_index, RAW_DATA, stored)
        print(f"[ancir]   {tp['name']}: {'ok' if ok else 'skipped/empty'}")

    # Dump all columns again (now reflecting TP outputs)
    rows = {}
    for c in columns_index.values():
        rows[c.name] = c.get_data()
    max_len = max((len(v) for v in rows.values()), default=0)
    for k in rows:
        rows[k] = list(rows[k]) + [None] * (max_len - len(rows[k]))
    df_final = pd.DataFrame(rows)
    df_final.to_csv(out_path / "columns_after_tables.csv", index=False)
    print(f"[ancir] wrote {out_path / 'columns_after_tables.csv'} "
          f"({len(df_final)} rows, {len(df_final.columns)} cols)")

    # Render plots
    if PLOTS:
        render_plots(PLOTS, columns_index, out_path)

    # Loud summary of any unsupported processes (only reachable when
    # STRICT_PROCESSES was set to False; strict mode aborts earlier).
    if UNSUPPORTED_PROCESSES:
        print("\\n" + "=" * 70)
        print("WARNING: the following processes are NOT implemented by the "
              "runtime.\\nTheir outputs are WRONG (the processes were skipped):")
        for kind, name in UNSUPPORTED_PROCESSES:
            print(f"  - [{kind}] {name}")
        print("=" * 70)


if __name__ == "__main__":
    main()
`;

/**
 * Strip the runtime's own numpy/pandas/scipy/`from __future__` imports — HEADER
 * re-declares them. Mirrors the loop in ancir_to_python.py:emit().
 * @param {string} runtimeSrc
 * @returns {string}
 */
function stripRuntimeImports(runtimeSrc) {
	const kept = [];
	for (const line of runtimeSrc.split('\n')) {
		if (
			line.startsWith('from __future__') ||
			line.startsWith('import ') ||
			line.startsWith('from ')
		) {
			if (
				line.includes('numpy') ||
				line.includes('pandas') ||
				line.includes('scipy') ||
				line.startsWith('from __future__')
			) {
				continue;
			}
		}
		kept.push(line);
	}
	return kept.join('\n');
}

/**
 * Pluck the JSON-serialisable metadata for a column. Mirrors
 * ancir_to_python.py:_col_meta_for_column — keys whose value is null are
 * dropped (except `processes`, which is always kept).
 * @param {any} col
 */
function colMetaForColumn(col) {
	const meta = {
		name: col.name ?? null,
		type: col.type ?? 'number',
		data: col.data ?? null,
		compression: col.compression ?? null,
		timeFormat: col.timeFormat ?? null,
		binWidth: col.binWidth ?? 1.0,
		refId: col.refId ?? null,
		groupLabel: col.groupLabel ?? null,
		processes: (col.processes ?? []).map((p) => ({
			funcname: p.funcname ?? null,
			name: p.name ?? null,
			args: p.args ?? {}
		}))
	};
	const out = {};
	for (const [k, v] of Object.entries(meta)) {
		if (v !== null || k === 'processes') out[k] = v;
	}
	return out;
}

// Embed a value the way the CLI does: `json.loads("<escaped json text>")`.
// JSON.stringify of the JSON text yields a string literal valid in both JSON
// and Python, mirroring the CLI's json.dumps(json.dumps(x)).
function embed(name, value) {
	return `${name} = json.loads(${JSON.stringify(JSON.stringify(value))})`;
}

// ----------------------------------------------------------------------
// Optional CSV data sidecar ("Export data as separate CSV")
//
// KEEP IN SYNC with rExport.js: both exporters must write byte-identical
// session_data.csv for the same session (one file serves either script), and
// neither file may import the other because both are inlined verbatim into
// their sidecars. A test compares their output.
// ----------------------------------------------------------------------

const DATA_CSV_NAME = 'session_data.csv';

/**
 * Classify a raw-data column for the CSV sidecar.
 * - 'num': every value is a finite number or null. Nulls become empty cells.
 * - 'str': every value is a NON-EMPTY string. (An empty string would be
 *   indistinguishable from a null/padding cell, so such columns stay inline.)
 * - null: anything else (mixed types, non-finite numbers, empty arrays) stays
 *   embedded inline, where the existing literal path already round-trips it.
 */
function csvKindFor(values) {
	if (!Array.isArray(values) || values.length === 0) return null;
	let allNum = true;
	let allStr = true;
	for (const v of values) {
		if (!(v === null || (typeof v === 'number' && Number.isFinite(v)))) allNum = false;
		if (!(typeof v === 'string' && v !== '')) allStr = false;
		if (!allNum && !allStr) return null;
	}
	return allNum ? 'num' : 'str';
}

/** One CSV cell. Numbers via JSON.stringify (shortest round-trip form, exactly
 *  what the inline path embeds); null → empty; RFC-4180 quoting for text. */
function csvCell(v) {
	if (v === null || v === undefined) return '';
	const s = typeof v === 'number' ? JSON.stringify(v) : String(v);
	return /[",\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
}

/**
 * Split rawData into CSV-able columns and an inline remainder.
 * Returns { inline, specs, csvText } where specs is [{id, kind, length}] in
 * CSV column order and csvText is null when nothing qualifies (the export then
 * silently stays fully inline rather than shipping an empty CSV).
 */
function splitRawDataForCsv(rawData) {
	const inline = {};
	const specs = [];
	const columns = [];
	for (const [key, values] of Object.entries(rawData ?? {})) {
		const kind = csvKindFor(values);
		if (kind === null) {
			inline[key] = values;
			continue;
		}
		specs.push({ id: /^-?\d+$/.test(key) ? Number(key) : key, kind, length: values.length });
		columns.push(values);
	}
	if (specs.length === 0) return { inline: rawData ?? {}, specs: [], csvText: null };
	const nRows = Math.max(...specs.map((s) => s.length));
	const lines = [specs.map((s) => csvCell(`col_${s.id}`)).join(',')];
	for (let r = 0; r < nRows; r++) {
		lines.push(columns.map((col) => (r < col.length ? csvCell(col[r]) : '')).join(','));
	}
	return { inline, specs, csvText: lines.join('\n') + '\n' };
}

// Reads the CSV sidecar back into RAW_DATA. Truncating to the recorded length
// separates real trailing nulls from rectangle padding; parsing 'num' cells as
// JSON keeps integers integers and floats at full precision, exactly matching
// what json.loads sees on the inline path.
const PY_CSV_LOADER = `# The column data lives in ${DATA_CSV_NAME}, exported alongside this script —
# keep both files in the same folder. Cells hold exactly what the inline
# export embeds: numbers at full precision, empty cells for missing values,
# text verbatim.
_csv_df = pd.read_csv(Path(__file__).with_name(${JSON.stringify(DATA_CSV_NAME)}),
                      dtype=str, keep_default_na=False)
for _spec in CSV_COLUMNS:
    _cells = list(_csv_df[f"col_{_spec['id']}"])[:_spec["length"]]
    if _spec["kind"] == "num":
        RAW_DATA[_spec["id"]] = [None if c == "" else json.loads(c) for c in _cells]
    else:
        RAW_DATA[_spec["id"]] = _cells
del _csv_df, _spec, _cells`;

/**
 * Nodes whose output is BAKED rather than re-run.
 *
 * Random and SimulatedData draw from the JS engine's seeded PRNG. Re-running them in another
 * language cannot reproduce that draw, so the exported script used to OVERWRITE the session's
 * real values with fresh ones — silently, on every run, with no warning. Measured on
 * demo-tp-random: the session holds 9.23, 3.33, 1.98, 9.49; two Python runs gave
 * 6.54/8.67/0.06/4.43 and 7.86/4.87/2.24/0.69.
 *
 * The session already carries what they produced — `rawData` holds each generated column
 * under its output id, which is how the app redraws it on load. So the fix is simply not to
 * run them again: the embedded data IS the result, and the script reproduces the session
 * exactly.
 *
 * `simulatedata` (one d) is the DISPLAY name "Simulate Data" with its space removed. Sessions
 * normally store the registry key, but the Python runtime keeps a display-name map because
 * some store the label instead — so both spellings are listed rather than assumed.
 *
 * Deterministic sources (SequenceColumn, BlankColumn) are NOT here. They re-run identically,
 * and leaving them in keeps the script showing how the column was built.
 *
 * Kept in sync with the R exporter by a test — neither file may import the other, because
 * both are inlined verbatim into their sidecars.
 */
const BAKED_NODES = ['random', 'simulateddata', 'simulatedata'];

/** Node name as stored ("Simulate Data", "SimulatedData") to its runtime key. */
function nodeKey(name) {
	return String(name ?? '')
		.toLowerCase()
		.replace(/\s+/g, '');
}

/**
 * The "# ----- Session data (embedded) -----" block shared by every export
 * shape. Returns { lines, csvText }; csvText is non-null only when dataAsCsv
 * found at least one CSV-able column.
 * @param {any} session
 * @param {boolean} dataAsCsv
 */
function dataSectionLines(session, dataAsCsv) {
	const rawData = session.rawData ?? {};
	const columns = session.data ?? [];
	// Analyses are free table-process nodes; legacy grouped `tables` are flattened
	// in for back-compat (mirrors the CLI).
	const tableProcesses = session.tableProcesses ?? [];
	const legacyTables = session.tables ?? [];
	const plots = session.plots ?? [];
	const storedValues = session.storedValues ?? {};

	/** @type {Record<number, any>} */
	const colMeta = {};
	for (const c of columns) {
		if (c?.id == null) continue;
		colMeta[c.id] = colMetaForColumn(c);
	}

	const tpsClean = [];
	for (const tp of tableProcesses) {
		if (BAKED_NODES.includes(nodeKey(tp.name))) continue;
		tpsClean.push({ name: tp.name ?? null, args: tp.args ?? {} });
	}
	for (const t of legacyTables) {
		for (const p of t.processes ?? []) {
			if (BAKED_NODES.includes(nodeKey(p.name))) continue;
			tpsClean.push({ name: p.name ?? null, args: p.args ?? {} });
		}
	}

	const { inline, specs, csvText } = dataAsCsv
		? splitRawDataForCsv(rawData)
		: { inline: rawData, specs: [], csvText: null };

	const lines = ['# ----- Session data (embedded) -----'];
	lines.push(embed('RAW_DATA', inline));
	lines.push(
		"RAW_DATA = {int(k) if k.lstrip('-').isdigit() else k: v for k, v in RAW_DATA.items()}"
	);
	if (csvText !== null) {
		lines.push(embed('CSV_COLUMNS', specs));
		lines.push(PY_CSV_LOADER);
	}
	lines.push(embed('_COL_META_RAW', colMeta));
	lines.push('COLUMN_META = {int(k): v for k, v in _COL_META_RAW.items()}');
	lines.push(embed('TABLE_PROCESSES', tpsClean));
	lines.push(embed('PLOTS', plots));
	lines.push(embed('STORED_VALUES', storedValues));
	return { lines, csvText };
}

/**
 * Header for the split-mode analysis script: same imports as HEADER, plus the
 * helper import and a version check that WARNS on skew rather than failing —
 * re-running old work still runs, but a mismatch is visible.
 * @param {string} version
 */
function analysisHeader(version) {
	return `#!/usr/bin/env python3
"""Generated by AnCiR — session analysis (experimental). Do not edit by hand.

Reproduces the analyses in an AnCiR session, in session order. The analysis
functions themselves live in ancir_helpers.py, exported alongside this file —
keep both (and any ${DATA_CSV_NAME}) in the SAME folder.

Requires: numpy, pandas, scipy. Run it (\`python this_file.py\`) to write
<name>_output/ with columns.csv, columns_after_tables.csv, and any plots.
"""
from __future__ import annotations
import json
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import optimize as sp_optimize, stats as sp_stats

from ancir_helpers import *  # noqa: F401,F403 — the AnCiR runtime

_EXPECTED_HELPERS_VERSION = ${JSON.stringify(version)}
if str(globals().get("ANCIR_HELPERS_VERSION", "<missing>")) != _EXPECTED_HELPERS_VERSION:
    print("[ancir] WARNING: ancir_helpers.py is version "
          f"{globals().get('ANCIR_HELPERS_VERSION', '<missing>')} but this script "
          f"was exported with {_EXPECTED_HELPERS_VERSION}. Results may differ.",
          file=sys.stderr)`;
}

/**
 * The helper file for split mode: the FULL runtime, verbatim (its own imports
 * intact, so it stands alone), stamped with the exporting AnCiR version. Only
 * comments go BEFORE the runtime — its module docstring and "from __future__"
 * import must stay first — so the version constant lands at the end.
 * @param {string} runtimeSrc
 * @param {string} version
 */
function helpersFile(runtimeSrc, version) {
	return `# Generated by AnCiR ${version} — analysis helper functions. Do not edit by hand.
# This file is the complete AnCiR Python runtime, identical for every session
# exported by this AnCiR version. The matching analysis script imports
# everything from it and checks ANCIR_HELPERS_VERSION (defined at the end).
# Requires: numpy, pandas, scipy.

${runtimeSrc}

# Version stamp checked by the analysis script exported with this file.
ANCIR_HELPERS_VERSION = ${JSON.stringify(version)}
`;
}

/**
 * Build a self-contained Python script reproducing `session`.
 * @param {any} session - parsed session object (as from outputCoreAsJson()).
 * @param {string} runtimeSrc - verbatim source of tools/ancir_runtime.py.
 * @returns {string} the Python script text.
 */
export function sessionToPython(session, runtimeSrc) {
	if (!session || typeof session !== 'object') {
		throw new Error('sessionToPython: invalid session object');
	}
	if (typeof runtimeSrc !== 'string' || !runtimeSrc) {
		throw new Error('sessionToPython: missing runtime source');
	}
	const { lines } = dataSectionLines(session, false);
	return [HEADER, '', stripRuntimeImports(runtimeSrc), '', ...lines, FOOTER_RUN].join('\n');
}

/**
 * Build the Python export as a set of files.
 *
 * Options:
 * - split: emit ancir_helpers.py (the full runtime, version-stamped) plus a
 *   short analysis.py holding only the session's data and pipeline. Default
 *   false → one self-contained session.py, identical to sessionToPython.
 * - dataAsCsv: move column data into session_data.csv, read back by the script
 *   with pandas.read_csv. Columns the CSV cannot represent losslessly stay
 *   embedded inline.
 * - version: the exporting AnCiR version, stamped into the helper file and
 *   checked by the analysis script ('dev' when absent).
 *
 * @param {any} session - parsed session object (as from outputCoreAsJson()).
 * @param {string} runtimeSrc - verbatim source of tools/ancir_runtime.py.
 * @param {{split?: boolean, dataAsCsv?: boolean, version?: string}} [options]
 * @returns {{name: string, text: string}[]} files to deliver together.
 */
export function sessionToPythonFiles(session, runtimeSrc, options = {}) {
	if (!session || typeof session !== 'object') {
		throw new Error('sessionToPythonFiles: invalid session object');
	}
	if (typeof runtimeSrc !== 'string' || !runtimeSrc) {
		throw new Error('sessionToPythonFiles: missing runtime source');
	}
	const opts = options ?? {};
	const split = opts.split === true;
	const dataAsCsv = opts.dataAsCsv === true;
	const version = typeof opts.version === 'string' && opts.version ? opts.version : 'dev';

	const { lines, csvText } = dataSectionLines(session, dataAsCsv);
	const files = [];
	if (!split) {
		files.push({
			name: 'session.py',
			text: [HEADER, '', stripRuntimeImports(runtimeSrc), '', ...lines, FOOTER_RUN].join('\n')
		});
	} else {
		files.push({
			name: 'analysis.py',
			text: [analysisHeader(version), '', ...lines, FOOTER_RUN].join('\n')
		});
		files.push({ name: 'ancir_helpers.py', text: helpersFile(runtimeSrc, version) });
	}
	if (csvText !== null) files.push({ name: DATA_CSV_NAME, text: csvText });
	return files;
}
