// @ts-nocheck
/**
 * Build a self-contained R script reproducing a session.
 *
 * Mirrors pythonExport.js, with one deliberate difference: the session is embedded as R
 * LITERALS rather than as JSON.
 *
 * Python can parse its own embedded JSON with the stdlib `json` module, so the Python export
 * writes `json.loads("...")`. Base R has no JSON parser — reading JSON would mean requiring
 * jsonlite, and every package a user has to install is friction on a feature whose whole
 * point is "run this and see". Emitting `list(...)` and `c(...)` keeps the script
 * dependency-free AND readable: someone can open it and see their own data.
 *
 * The runtime it embeds (tools/ancir_runtime.R) is base R throughout for the same reason.
 */

const HEADER = `#!/usr/bin/env Rscript
# Generated by AnCiR — export session as R (experimental). Do not edit by hand.
#
# Reproduces the analyses in an AnCiR session. Requires nothing beyond base R.
# Run it (\`Rscript this_file.R\`, or source() it from anywhere) to write
# <name>_output/ next to this script, with columns.csv and
# columns_after_analyses.csv.
`;

// ----------------------------------------------------------------------
// Script location. Emitted exactly ONCE per exported script, near the top,
// because everything else (source() of the helpers, the CSV loader, the
// output directory) resolves paths through it. v72.23 shipped this helper
// duplicated (header + CSV loader + pipeline footer) and resolving ONLY via
// commandArgs()/--file=, which does not exist in RStudio or an interactive
// console — hence the fallback chain and the ANCIR_DIR user override below.
// ----------------------------------------------------------------------
const R_SCRIPT_DIR_BLOCK = `## If automatic detection fails (e.g. pasting into a console), set this to the
## folder containing this script's companion files (ancir_helpers.R and/or
## session_data.csv, where exported), e.g.
## ANCIR_DIR <- "/path/to/exported/files"
ANCIR_DIR <- NULL

# Full path of this script when detectable, NA otherwise. Tries, in order:
# --file= from commandArgs (Rscript), the source() call stack (source("...")
# from any working directory), then the document open in RStudio.
script_file <- function() {
  f <- sub("^--file=", "", grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE))
  if (length(f) >= 1 && nzchar(f[1])) return(normalizePath(f[1], mustWork = FALSE))
  for (fr in rev(sys.frames())) {
    of <- fr$ofile
    if (is.character(of) && length(of) == 1 && nzchar(of)) {
      return(normalizePath(of, mustWork = FALSE))
    }
  }
  if (requireNamespace("rstudioapi", quietly = TRUE)) {
    p <- tryCatch(rstudioapi::getActiveDocumentContext()$path, error = function(e) "")
    if (is.character(p) && length(p) == 1 && nzchar(p)) {
      return(normalizePath(p, mustWork = FALSE))
    }
  }
  NA_character_
}

# Folder holding this script and its companion files. ANCIR_DIR (above) wins;
# then the detected script location; last resort is the working directory.
script_dir <- function() {
  if (!is.null(ANCIR_DIR)) return(ANCIR_DIR)
  f <- script_file()
  if (!is.na(f)) return(dirname(f))
  message("[ancir] Could not determine this script's location; looking for its ",
          "companion files in the current working directory (", getwd(), "). ",
          "If that is wrong, set ANCIR_DIR at the top of this script, or setwd().")
  getwd()
}`;

const FOOTER_RUN = `

# ----------------------------------------------------------------------
# Pipeline
# ----------------------------------------------------------------------

main <- function() {
  env <- new.env()
  env$raw_data <- RAW_DATA
  env$cols <- list()
  for (cid in names(COLUMN_META)) {
    meta <- COLUMN_META[[cid]]
    env$cols[[cid]] <- new_column(
      id = as.numeric(cid),
      name = meta$name,
      type = if (is.null(meta$type)) "number" else meta$type,
      data = meta$data,
      time_format = meta$timeFormat,
      bin_width = if (is.null(meta$binWidth)) 1 else meta$binWidth,
      compression = meta$compression,
      ref_id = meta$refId,
      group_label = meta$groupLabel,
      processes = if (is.null(meta$processes)) list() else meta$processes
    )
  }

  # Output goes NEXT TO the script (not the working directory), named after it,
  # so source()-ing from another directory still puts results with the export.
  script <- script_file()
  base <- if (is.na(script)) "session" else tools::file_path_sans_ext(basename(script))
  out_dir <- file.path(script_dir(), paste0(base, "_output"))
  dir.create(out_dir, showWarnings = FALSE)

  dump_columns <- function(path) {
    rows <- list()
    for (cid in names(env$cols)) {
      col <- env$cols[[cid]]
      nm <- if (is.null(col$name) || !nzchar(col$name)) paste0("col_", cid) else col$name
      # Duplicate names would silently overwrite each other in the data frame, so later
      # ones are suffixed rather than lost.
      base <- nm; k <- 2
      while (!is.null(rows[[nm]])) { nm <- paste0(base, "_", k); k <- k + 1 }
      rows[[nm]] <- unlist(col_data(col, env$cols, env$raw_data), use.names = FALSE)
    }
    if (!length(rows)) return(invisible(NULL))
    n <- max(vapply(rows, length, integer(1)))
    # Columns have different lengths (an analysis output is shorter than its input), so they
    # are padded to a rectangle rather than recycled — recycling would invent data.
    rows <- lapply(rows, function(v) c(v, rep(NA, n - length(v))))
    # check.names = FALSE: R's default would munge "Set I" into "Set.I" and "x (sets I-III)"
    # into "x..sets.I.III.", so the CSV headers would silently disagree with the app's column
    # names and with the Python export's, for identical data.
    df <- as.data.frame(rows, stringsAsFactors = FALSE, check.names = FALSE)
    write.csv(df, path, row.names = FALSE)
    cat(sprintf("[ancir] wrote %s (%d rows, %d cols)\\n", path, n, length(rows)))
  }

  dump_columns(file.path(out_dir, "columns.csv"))

  # Analyses run in creation order, which respects their dependencies: each writes into
  # env$raw_data, so a later one sees an earlier one's output columns.
  #
  # STRICT: an analysis this runtime does not implement ABORTS here rather than being
  # skipped. A script that quietly omits a step still writes a plausible columns.csv, and a
  # plausible file with a missing analysis is more dangerous than no file at all.
  for (tp in TABLE_PROCESSES) {
    ok <- run_table_process(tp$name, tp$args, env)
    cat(sprintf("[ancir]   %s: %s\\n", tp$name, if (isTRUE(ok)) "ok" else "skipped/empty"))
  }

  dump_columns(file.path(out_dir, "columns_after_analyses.csv"))
}

main()
`;

/**
 * Serialise a JS value as an R literal.
 *
 * Objects become named `list()`, arrays become `list()` too rather than `c()`: `c()` FLATTENS
 * nested structures and coerces mixed types to character, either of which would silently
 * reshape a session. Numeric leaf arrays are the one exception, emitted as `c()` so column
 * data stays a plain vector — which is what every kernel expects.
 */
export function toRLiteral(value) {
	if (value === null || value === undefined) return 'NULL';
	if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
	if (typeof value === 'number') {
		if (Number.isNaN(value)) return 'NA_real_';
		if (value === Infinity) return 'Inf';
		if (value === -Infinity) return '-Inf';
		return String(value);
	}
	if (typeof value === 'string') return JSON.stringify(value);
	if (Array.isArray(value)) {
		if (value.length === 0) return 'list()';
		// A pure numeric/null array is column data: emit a real vector.
		const numericish = value.every(
			(v) => v === null || v === undefined || (typeof v === 'number' && !Number.isNaN(v))
		);
		if (numericish) {
			return `c(${value.map((v) => (v === null || v === undefined ? 'NA' : toRLiteral(v))).join(', ')})`;
		}
		return `list(${value.map(toRLiteral).join(', ')})`;
	}
	if (typeof value === 'object') {
		const entries = Object.entries(value);
		if (entries.length === 0) return 'list()';
		return `list(${entries
			.map(([k, v]) => `${JSON.stringify(String(k))} = ${toRLiteral(v)}`)
			.join(', ')})`;
	}
	return 'NULL';
}

// R's console (and RStudio's) truncates any single INPUT line at 4094 chars
// ("WARNING: Truncating console input of length ..."), so a script whose data
// literal is one enormous line breaks for anyone stepping through it
// interactively — which is exactly how R users work through an analysis.
// source()/Rscript have no such limit, but the generated file must serve both.
// The wrap point targets well under the limit so the continuation indent and
// any measurement slack never push a line over it.
const R_MAX_LINE = 3800;

/**
 * Wrap one generated R line to at most `max` characters per physical line by
 * breaking after commas that sit OUTSIDE string literals. Every generated
 * over-long line is a single assignment to a `list(...)`/`c(...)` literal, so
 * every such comma is inside an open call and R parses the expression as
 * continuing across the newline. Strings are double-quoted with backslash
 * escapes (JSON.stringify), which the scanner tracks so a comma inside data
 * text is never a break point. A pathological single token longer than `max`
 * (one enormous string) is left intact — it cannot be split without changing
 * its value.
 */
export function wrapRLine(line, max = R_MAX_LINE) {
	if (line.length <= max) return line;
	const parts = [];
	let start = 0;
	let inStr = false;
	let lastBreak = -1;
	for (let i = 0; i < line.length; i++) {
		const ch = line[i];
		if (inStr) {
			if (ch === '\\') i++;
			else if (ch === '"') inStr = false;
		} else if (ch === '"') {
			inStr = true;
		} else if (ch === ',') {
			lastBreak = i;
		}
		if (i - start >= max) {
			const br = lastBreak > start ? lastBreak : !inStr && ch === ',' ? i : -1;
			if (br > start) {
				parts.push(line.slice(start, br + 1));
				start = br + 1;
				lastBreak = -1;
			}
		}
	}
	if (start < line.length) parts.push(line.slice(start));
	return parts.map((s, idx) => (idx === 0 ? s : '  ' + s)).join('\n');
}

/** wrapRLine over every line of a generated block. */
function wrapRLines(lines) {
	return lines.map((l) =>
		l
			.split('\n')
			.map((one) => wrapRLine(one))
			.join('\n')
	);
}

/**
 * Nodes whose output is BAKED rather than re-run.
 *
 * Random and SimulatedData draw from the JS engine's seeded PRNG. Re-running them in another
 * language cannot reproduce that draw, so the exported script used to OVERWRITE the session's
 * real values with fresh ones — silently, on every run, with no warning. Measured on
 * demo-tp-random: the session holds 9.23, 3.33, 1.98, 9.49; two Python runs gave
 * 6.54/8.67/0.06/4.43 and 7.86/4.87/2.24/0.69.
 *
 * The session already carries what they produced — `rawData` holds each generated column
 * under its output id, which is how the app redraws it on load. So the fix is simply not to
 * run them again: the embedded data IS the result, and the script reproduces the session
 * exactly.
 *
 * `simulatedata` (one d) is the DISPLAY name "Simulate Data" with its space removed. Sessions
 * normally store the registry key, but the Python runtime keeps a display-name map because
 * some store the label instead — so both spellings are listed rather than assumed.
 *
 * Deterministic sources (SequenceColumn, BlankColumn) are NOT here. They re-run identically,
 * and leaving them in keeps the script showing how the column was built.
 *
 * Kept in sync with the R exporter by a test — neither file may import the other, because
 * both are inlined verbatim into their sidecars.
 */
const BAKED_NODES = ['random', 'simulateddata', 'simulatedata'];

/** Node name as stored ("Simulate Data", "SimulatedData") to its runtime key. */
function nodeKey(name) {
	return String(name ?? '')
		.toLowerCase()
		.replace(/\s+/g, '');
}

/** Column metadata, mirroring pythonExport.js:colMetaForColumn. */
function colMetaForColumn(col) {
	const meta = {
		name: col.name ?? null,
		type: col.type ?? 'number',
		data: col.data ?? null,
		compression: col.compression ?? null,
		timeFormat: col.timeFormat ?? null,
		binWidth: col.binWidth ?? 1.0,
		refId: col.refId ?? null,
		groupLabel: col.groupLabel ?? null,
		processes: (col.processes ?? []).map((p) => ({
			funcname: p.funcname ?? null,
			name: p.name ?? null,
			args: p.args ?? {}
		}))
	};
	const out = {};
	for (const [k, v] of Object.entries(meta)) {
		if (v !== null || k === 'processes') out[k] = v;
	}
	return out;
}

// ----------------------------------------------------------------------
// Optional CSV data sidecar ("Export data as separate CSV")
//
// KEEP IN SYNC with pythonExport.js: both exporters must write byte-identical
// session_data.csv for the same session (one file serves either script), and
// neither file may import the other because both are inlined verbatim into
// their sidecars. A test compares their output.
// ----------------------------------------------------------------------

const DATA_CSV_NAME = 'session_data.csv';

/**
 * Classify a raw-data column for the CSV sidecar.
 * - 'num': every value is a finite number or null. Nulls become empty cells.
 * - 'str': every value is a NON-EMPTY string. (An empty string would be
 *   indistinguishable from a null/padding cell, so such columns stay inline.)
 * - null: anything else (mixed types, non-finite numbers, empty arrays) stays
 *   embedded inline, where toRLiteral already round-trips it.
 */
function csvKindFor(values) {
	if (!Array.isArray(values) || values.length === 0) return null;
	let allNum = true;
	let allStr = true;
	for (const v of values) {
		if (!(v === null || (typeof v === 'number' && Number.isFinite(v)))) allNum = false;
		if (!(typeof v === 'string' && v !== '')) allStr = false;
		if (!allNum && !allStr) return null;
	}
	return allNum ? 'num' : 'str';
}

/** One CSV cell. Numbers via JSON.stringify (shortest round-trip form, exactly
 *  what the inline path embeds); null → empty; RFC-4180 quoting for text. */
function csvCell(v) {
	if (v === null || v === undefined) return '';
	const s = typeof v === 'number' ? JSON.stringify(v) : String(v);
	return /[",\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
}

/**
 * Split rawData into CSV-able columns and an inline remainder.
 * Returns { inline, specs, csvText }; csvText is null when nothing qualifies
 * (the export then silently stays fully inline rather than shipping an empty CSV).
 */
function splitRawDataForCsv(rawData) {
	const inline = {};
	const specs = [];
	const columns = [];
	for (const [key, values] of Object.entries(rawData ?? {})) {
		const kind = csvKindFor(values);
		if (kind === null) {
			inline[key] = values;
			continue;
		}
		specs.push({ id: /^-?\d+$/.test(key) ? Number(key) : key, kind, length: values.length });
		columns.push(values);
	}
	if (specs.length === 0) return { inline: rawData ?? {}, specs: [], csvText: null };
	const nRows = Math.max(...specs.map((s) => s.length));
	const lines = [specs.map((s) => csvCell(`col_${s.id}`)).join(',')];
	for (let r = 0; r < nRows; r++) {
		lines.push(columns.map((col) => (r < col.length ? csvCell(col[r]) : '')).join(','));
	}
	return { inline, specs, csvText: lines.join('\n') + '\n' };
}

// Reads the CSV sidecar back into RAW_DATA. Everything is read as character
// first (na.strings = character(0), so a literal "NA" string survives), then
// truncated to the recorded length — separating real trailing nulls from
// rectangle padding — and converted per the column's kind: 'num' → numeric
// vector with NA for empty cells (what the inline c(...) literal holds),
// 'str' → list of strings (what the inline list(...) literal holds).
// Resolves the CSV via script_dir(), defined ONCE near the top of the script.
const R_CSV_LOADER = `# The column data lives in ${DATA_CSV_NAME}, exported alongside this script —
# keep both files in the same folder (or point ANCIR_DIR, above, at it).
# Cells hold exactly what the inline export embeds: numbers at full
# precision, empty cells for missing values, text verbatim.
local({
  df <- read.csv(file.path(script_dir(), ${JSON.stringify(DATA_CSV_NAME)}),
                 colClasses = "character", check.names = FALSE,
                 na.strings = character(0))
  for (spec in CSV_COLUMNS) {
    cells <- df[[paste0("col_", spec$id)]][seq_len(spec$length)]
    RAW_DATA[[as.character(spec$id)]] <<- if (identical(spec$kind, "num")) {
      v <- suppressWarnings(as.numeric(cells)); v[!nzchar(cells)] <- NA; v
    } else {
      as.list(cells)
    }
  }
})`;

/**
 * The "# ----- Session data (embedded) -----" block shared by every export
 * shape. Returns { lines, csvText }; csvText is non-null only when dataAsCsv
 * found at least one CSV-able column.
 * @param {any} session
 * @param {boolean} dataAsCsv
 */
function dataSectionLines(session, dataAsCsv) {
	const rawData = session.rawData ?? {};
	const columns = session.data ?? [];
	// Analyses are free table-process nodes; legacy grouped `tables` are flattened in for
	// back-compat, mirroring the Python export and the CLI.
	const tableProcesses = session.tableProcesses ?? [];
	const legacyTables = session.tables ?? [];

	const colMeta = {};
	for (const c of columns) {
		if (c?.id == null) continue;
		colMeta[c.id] = colMetaForColumn(c);
	}

	const tpsClean = [];
	for (const tp of tableProcesses) {
		if (BAKED_NODES.includes(nodeKey(tp.name))) continue;
		tpsClean.push({ name: tp.name ?? null, args: tp.args ?? {} });
	}
	for (const t of legacyTables) {
		for (const p of t.processes ?? []) {
			if (BAKED_NODES.includes(nodeKey(p.name))) continue;
			tpsClean.push({ name: p.name ?? null, args: p.args ?? {} });
		}
	}

	const { inline, specs, csvText } = dataAsCsv
		? splitRawDataForCsv(rawData)
		: { inline: rawData, specs: [], csvText: null };

	const lines = ['# ----- Session data (embedded) -----'];
	lines.push(`RAW_DATA <- ${toRLiteral(inline)}`);
	if (csvText !== null) {
		lines.push(`CSV_COLUMNS <- ${toRLiteral(specs)}`);
		lines.push(R_CSV_LOADER);
	}
	lines.push(`COLUMN_META <- ${toRLiteral(colMeta)}`);
	lines.push(`TABLE_PROCESSES <- ${toRLiteral(tpsClean)}`);
	return { lines: wrapRLines(lines), csvText };
}

/**
 * Header for the split-mode analysis script: sources ancir_helpers.R from its
 * own directory, then checks the helper version — WARNING on skew rather than
 * failing, so re-running old work still runs but a mismatch is visible.
 * @param {string} version
 */
function analysisHeader(version) {
	return `#!/usr/bin/env Rscript
# Generated by AnCiR — session analysis (experimental). Do not edit by hand.
#
# Reproduces the analyses in an AnCiR session, in session order. The analysis
# functions live in ancir_helpers.R, exported alongside this file — keep both
# (and any ${DATA_CSV_NAME}) in the SAME folder. Requires nothing beyond base R.
# Run it (\`Rscript this_file.R\`, or source() it from anywhere) to write
# <name>_output/ next to this script, with columns.csv and
# columns_after_analyses.csv.

${R_SCRIPT_DIR_BLOCK}

source(file.path(script_dir(), "ancir_helpers.R"))

.expected_helpers <- ${JSON.stringify(version)}
if (!exists("ANCIR_HELPERS_VERSION") || !identical(ANCIR_HELPERS_VERSION, .expected_helpers)) {
  message(sprintf(
    "[ancir] WARNING: ancir_helpers.R is version %s but this script was exported with %s. Results may differ.",
    if (exists("ANCIR_HELPERS_VERSION")) ANCIR_HELPERS_VERSION else "<missing>",
    .expected_helpers))
}`;
}

/**
 * The helper file for split mode: the FULL runtime, verbatim, stamped with the
 * exporting AnCiR version.
 * @param {string} runtimeSrc
 * @param {string} version
 */
function helpersFile(runtimeSrc, version) {
	return `# Generated by AnCiR ${version} — analysis helper functions. Do not edit by hand.
# This file is the complete AnCiR R runtime, identical for every session
# exported by this AnCiR version. The matching analysis script sources it and
# checks ANCIR_HELPERS_VERSION (defined at the end). Base R only.

${runtimeSrc}

# Version stamp checked by the analysis script exported with this file.
ANCIR_HELPERS_VERSION <- ${JSON.stringify(version)}
`;
}

/**
 * Build a self-contained R script reproducing `session`.
 * @param {any} session - parsed session object (as from outputCoreAsJson()).
 * @param {string} runtimeSrc - verbatim source of tools/ancir_runtime.R.
 * @returns {string} the R script text.
 */
export function sessionToR(session, runtimeSrc) {
	if (!session || typeof session !== 'object') {
		throw new Error('sessionToR: invalid session object');
	}
	if (typeof runtimeSrc !== 'string' || !runtimeSrc) {
		throw new Error('sessionToR: missing runtime source');
	}
	const { lines } = dataSectionLines(session, false);
	return [HEADER, R_SCRIPT_DIR_BLOCK, '', runtimeSrc, '', ...lines, FOOTER_RUN].join('\n');
}

/**
 * Build the R export as a set of files.
 *
 * Options (mirroring sessionToPythonFiles):
 * - split: emit ancir_helpers.R (the full runtime, version-stamped) plus a
 *   short analysis.R holding only the session's data and pipeline. Default
 *   false → one self-contained session.R, identical to sessionToR.
 * - dataAsCsv: move column data into session_data.csv, read back by the script
 *   with read.csv. Columns the CSV cannot represent losslessly stay inline.
 * - version: the exporting AnCiR version, stamped into the helper file and
 *   checked by the analysis script ('dev' when absent).
 *
 * @param {any} session - parsed session object (as from outputCoreAsJson()).
 * @param {string} runtimeSrc - verbatim source of tools/ancir_runtime.R.
 * @param {{split?: boolean, dataAsCsv?: boolean, version?: string}} [options]
 * @returns {{name: string, text: string}[]} files to deliver together.
 */
export function sessionToRFiles(session, runtimeSrc, options = {}) {
	if (!session || typeof session !== 'object') {
		throw new Error('sessionToRFiles: invalid session object');
	}
	if (typeof runtimeSrc !== 'string' || !runtimeSrc) {
		throw new Error('sessionToRFiles: missing runtime source');
	}
	const opts = options ?? {};
	const split = opts.split === true;
	const dataAsCsv = opts.dataAsCsv === true;
	const version = typeof opts.version === 'string' && opts.version ? opts.version : 'dev';

	const { lines, csvText } = dataSectionLines(session, dataAsCsv);
	const files = [];
	if (!split) {
		files.push({
			name: 'session.R',
			text: [HEADER, R_SCRIPT_DIR_BLOCK, '', runtimeSrc, '', ...lines, FOOTER_RUN].join('\n')
		});
	} else {
		files.push({
			name: 'analysis.R',
			text: [analysisHeader(version), '', ...lines, FOOTER_RUN].join('\n')
		});
		files.push({ name: 'ancir_helpers.R', text: helpersFile(runtimeSrc, version) });
	}
	if (csvText !== null) files.push({ name: DATA_CSV_NAME, text: csvText });
	return files;
}
