// @ts-nocheck
/**
 * Build a self-contained R script reproducing a session.
 *
 * Mirrors pythonExport.js, with one deliberate difference: the session is embedded as R
 * LITERALS rather than as JSON.
 *
 * Python can parse its own embedded JSON with the stdlib `json` module, so the Python export
 * writes `json.loads("...")`. Base R has no JSON parser — reading JSON would mean requiring
 * jsonlite, and every package a user has to install is friction on a feature whose whole
 * point is "run this and see". Emitting `list(...)` and `c(...)` keeps the script
 * dependency-free AND readable: someone can open it and see their own data.
 *
 * The runtime it embeds (tools/ancir_runtime.R) is base R throughout for the same reason.
 */

const HEADER = `#!/usr/bin/env Rscript
# Generated by AnCiR — export session as R (experimental). Do not edit by hand.
#
# Reproduces the analyses in an AnCiR session. Requires nothing beyond base R.
# Run it (\`Rscript this_file.R\`) to write <name>_output/ with columns.csv and
# columns_after_analyses.csv.
`;

const FOOTER_RUN = `

# ----------------------------------------------------------------------
# Pipeline
# ----------------------------------------------------------------------

main <- function() {
  env <- new.env()
  env$raw_data <- RAW_DATA
  env$cols <- list()
  for (cid in names(COLUMN_META)) {
    meta <- COLUMN_META[[cid]]
    env$cols[[cid]] <- new_column(
      id = as.numeric(cid),
      name = meta$name,
      type = if (is.null(meta$type)) "number" else meta$type,
      data = meta$data,
      time_format = meta$timeFormat,
      bin_width = if (is.null(meta$binWidth)) 1 else meta$binWidth,
      compression = meta$compression,
      ref_id = meta$refId,
      group_label = meta$groupLabel,
      processes = if (is.null(meta$processes)) list() else meta$processes
    )
  }

  out_dir <- paste0(tools::file_path_sans_ext(basename(script_path())), "_output")
  dir.create(out_dir, showWarnings = FALSE)

  dump_columns <- function(path) {
    rows <- list()
    for (cid in names(env$cols)) {
      col <- env$cols[[cid]]
      nm <- if (is.null(col$name) || !nzchar(col$name)) paste0("col_", cid) else col$name
      # Duplicate names would silently overwrite each other in the data frame, so later
      # ones are suffixed rather than lost.
      base <- nm; k <- 2
      while (!is.null(rows[[nm]])) { nm <- paste0(base, "_", k); k <- k + 1 }
      rows[[nm]] <- unlist(col_data(col, env$cols, env$raw_data), use.names = FALSE)
    }
    if (!length(rows)) return(invisible(NULL))
    n <- max(vapply(rows, length, integer(1)))
    # Columns have different lengths (an analysis output is shorter than its input), so they
    # are padded to a rectangle rather than recycled — recycling would invent data.
    rows <- lapply(rows, function(v) c(v, rep(NA, n - length(v))))
    # check.names = FALSE: R's default would munge "Set I" into "Set.I" and "x (sets I-III)"
    # into "x..sets.I.III.", so the CSV headers would silently disagree with the app's column
    # names and with the Python export's, for identical data.
    df <- as.data.frame(rows, stringsAsFactors = FALSE, check.names = FALSE)
    write.csv(df, path, row.names = FALSE)
    cat(sprintf("[ancir] wrote %s (%d rows, %d cols)\\n", path, n, length(rows)))
  }

  dump_columns(file.path(out_dir, "columns.csv"))

  # Analyses run in creation order, which respects their dependencies: each writes into
  # env$raw_data, so a later one sees an earlier one's output columns.
  #
  # STRICT: an analysis this runtime does not implement ABORTS here rather than being
  # skipped. A script that quietly omits a step still writes a plausible columns.csv, and a
  # plausible file with a missing analysis is more dangerous than no file at all.
  for (tp in TABLE_PROCESSES) {
    ok <- run_table_process(tp$name, tp$args, env)
    cat(sprintf("[ancir]   %s: %s\\n", tp$name, if (isTRUE(ok)) "ok" else "skipped/empty"))
  }

  dump_columns(file.path(out_dir, "columns_after_analyses.csv"))
}

# Path of this script, so the output directory is named after it however it was invoked.
script_path <- function() {
  a <- commandArgs(trailingOnly = FALSE)
  f <- sub("^--file=", "", grep("^--file=", a, value = TRUE))
  if (length(f)) f[1] else "session"
}

main()
`;

/**
 * Serialise a JS value as an R literal.
 *
 * Objects become named `list()`, arrays become `list()` too rather than `c()`: `c()` FLATTENS
 * nested structures and coerces mixed types to character, either of which would silently
 * reshape a session. Numeric leaf arrays are the one exception, emitted as `c()` so column
 * data stays a plain vector — which is what every kernel expects.
 */
export function toRLiteral(value) {
	if (value === null || value === undefined) return 'NULL';
	if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
	if (typeof value === 'number') {
		if (Number.isNaN(value)) return 'NA_real_';
		if (value === Infinity) return 'Inf';
		if (value === -Infinity) return '-Inf';
		return String(value);
	}
	if (typeof value === 'string') return JSON.stringify(value);
	if (Array.isArray(value)) {
		if (value.length === 0) return 'list()';
		// A pure numeric/null array is column data: emit a real vector.
		const numericish = value.every(
			(v) => v === null || v === undefined || (typeof v === 'number' && !Number.isNaN(v))
		);
		if (numericish) {
			return `c(${value.map((v) => (v === null || v === undefined ? 'NA' : toRLiteral(v))).join(', ')})`;
		}
		return `list(${value.map(toRLiteral).join(', ')})`;
	}
	if (typeof value === 'object') {
		const entries = Object.entries(value);
		if (entries.length === 0) return 'list()';
		return `list(${entries
			.map(([k, v]) => `${JSON.stringify(String(k))} = ${toRLiteral(v)}`)
			.join(', ')})`;
	}
	return 'NULL';
}

/** Column metadata, mirroring pythonExport.js:colMetaForColumn. */
function colMetaForColumn(col) {
	const meta = {
		name: col.name ?? null,
		type: col.type ?? 'number',
		data: col.data ?? null,
		compression: col.compression ?? null,
		timeFormat: col.timeFormat ?? null,
		binWidth: col.binWidth ?? 1.0,
		refId: col.refId ?? null,
		groupLabel: col.groupLabel ?? null,
		processes: (col.processes ?? []).map((p) => ({
			funcname: p.funcname ?? null,
			name: p.name ?? null,
			args: p.args ?? {}
		}))
	};
	const out = {};
	for (const [k, v] of Object.entries(meta)) {
		if (v !== null || k === 'processes') out[k] = v;
	}
	return out;
}

/**
 * Build a self-contained R script reproducing `session`.
 * @param {any} session - parsed session object (as from outputCoreAsJson()).
 * @param {string} runtimeSrc - verbatim source of tools/ancir_runtime.R.
 * @returns {string} the R script text.
 */
export function sessionToR(session, runtimeSrc) {
	if (!session || typeof session !== 'object') {
		throw new Error('sessionToR: invalid session object');
	}
	if (typeof runtimeSrc !== 'string' || !runtimeSrc) {
		throw new Error('sessionToR: missing runtime source');
	}

	const rawData = session.rawData ?? {};
	const columns = session.data ?? [];
	// Analyses are free table-process nodes; legacy grouped `tables` are flattened in for
	// back-compat, mirroring the Python export and the CLI.
	const tableProcesses = session.tableProcesses ?? [];
	const legacyTables = session.tables ?? [];

	const colMeta = {};
	for (const c of columns) {
		if (c?.id == null) continue;
		colMeta[c.id] = colMetaForColumn(c);
	}

	const tpsClean = [];
	for (const tp of tableProcesses) {
		tpsClean.push({ name: tp.name ?? null, args: tp.args ?? {} });
	}
	for (const t of legacyTables) {
		for (const p of t.processes ?? []) {
			tpsClean.push({ name: p.name ?? null, args: p.args ?? {} });
		}
	}

	const parts = [HEADER, '', runtimeSrc, ''];
	parts.push('# ----- Session data (embedded) -----');
	parts.push(`RAW_DATA <- ${toRLiteral(rawData)}`);
	parts.push(`COLUMN_META <- ${toRLiteral(colMeta)}`);
	parts.push(`TABLE_PROCESSES <- ${toRLiteral(tpsClean)}`);
	parts.push(FOOTER_RUN);

	return parts.join('\n');
}
