<script>
  import ChapterExamples from "$lib/components/ChapterExamples.svelte";
  import ChapterSection from "$lib/components/ChapterSection.svelte";
  import HistoricalContext from "$lib/components/HistoricalContext.svelte";
  import ParamTable from "$lib/components/ParamTable.svelte";
  import NoteBox from "$lib/components/NoteBox.svelte";
  import SineAnim from "$lib/animations/SineAnim.svelte";
  import MolecularAnim from "$lib/animations/MolecularAnim.svelte";
</script>

<ChapterSection id="ch1" num="Chapter 1" title="Introduction to Chronobiology">
  <HistoricalContext
    entries={[
      {
        year: "1729",
        text: "Jean-Jacques d&rsquo;Ortous de Mairan reports (published 1731) that a sensitive plant (traditionally identified as <em>Mimosa pudica</em>) keeps its daily leaf movements in complete darkness — the first record of a daily rhythm persisting without sunlight. De Mairan himself did not claim the rhythm was internally generated; that interpretation came much later.",
      },
      {
        year: 1751,
        text: "Carl Linnaeus designs his &quot;Horologium Florae&quot; (Flower Clock), exploiting predictable daily timing of floral opening across species.",
      },
      {
        year: "1950s–80s",
        text: "J&uuml;rgen Aschoff and Colin Pittendrigh dominate the field, establishing formal rules of circadian entrainment and coining many terms still in use today. Aschoff introduced the term <em>Zeitgeber</em> in the early 1950s.",
      },
      {
        year: 2017,
        text: 'Jeffrey Hall, Michael Rosbash, and Michael Young awarded the Nobel Prize in Physiology or Medicine for discovering the molecular mechanisms of the circadian clock.<sup class="cite"><a href="#ref-14">[14]</a></sup>',
      },
    ]}
  />

  <h3 class="section-head">What is a Biological Rhythm?</h3>
  <p>
    A biological rhythm is any periodic, self-sustaining oscillation in a
    physiological, biochemical, or behavioural process. Rhythms are
    characterised by four key parameters:
  </p>
  <ParamTable
    headers={["Parameter", "Definition"]}
    rows={[
      [
        "<strong>Period (τ)</strong>",
        "The time to complete one full cycle. For circadian rhythms, τ ≈ 24 hours.",
      ],
      [
        "<strong>Amplitude (A)</strong>",
        "Half the peak-to-trough difference — a measure of rhythm strength.",
      ],
      [
        "<strong>Phase (φ)</strong>",
        "The timing of a reference point (e.g., peak or onset) relative to a fixed time.",
      ],
      [
        "<strong>MESOR (M)</strong>",
        "Midline Estimating Statistic Of Rhythm — the rhythm-adjusted mean level.",
      ],
    ]}
  />
  <p>
    Biological rhythms are classified by <a class="gloss" href="#gloss-period">period</a> length. <a class="gloss" href="#gloss-circadian-rhythm"><strong
      >Circadian</strong
    ></a>
    rhythms (Latin:
    <em>circa diem</em>, 'about a day') have periods of ~24 hours.
    <a class="gloss" href="#gloss-ultradian"><strong>Ultradian</strong></a>
    rhythms are shorter than 24 hours (e.g., REM sleep cycles ~90 min);
    <a class="gloss" href="#gloss-infradian"><strong>infradian</strong></a> rhythms are longer (e.g., menstrual cycle ~28 days).
  </p>

  <SineAnim height="500px" />

  <h3 class="section-head">The Circadian Clock</h3>
  <p>
    Circadian rhythms are generated by endogenous molecular clocks present in
    virtually every cell. In mammals, the master pacemaker is the <a class="gloss" href="#gloss-scn"><strong
      >suprachiasmatic nucleus (SCN)</strong
    ></a> of the anterior hypothalamus. The molecular clockwork is built on a transcription-translation
    feedback loop (a process where proteins made from a gene gradually switch that
    same gene off, creating a ~24-hour cycle):
  </p>

  <ul>
    <li>
      <strong>CLOCK</strong> and <strong>BMAL1</strong> drive transcription of
      <em>Period (PER1/2/3)</em> and <em>Cryptochrome (CRY1/2)</em> genes.
    </li>
    <li>
      PER and CRY proteins accumulate over several hours, then feed back to
      inhibit CLOCK/BMAL1 activity.
    </li>
    <li>
      As PER and CRY are degraded (~24 hours), CLOCK/BMAL1-driven transcription
      restarts.
    </li>
    <li>
      Secondary stabilising loops involving REV-ERBα/β and RORα add robustness.
    </li>
  </ul>
  <NoteBox title="Key Point">
    <p>
      The intrinsic period (<a class="gloss" href="#gloss-free-running-period">free-running period, τ</a>) is rarely exactly 24 hours —
      in humans the average is ~24.2 hours<sup class="cite"><a href="#ref-17">[17]</a></sup>. Daily synchronisation (<a class="gloss" href="#gloss-entrainment">entrainment</a>)
      requires external time cues called <a class="gloss" href="#gloss-zeitgeber"><strong>zeitgebers</strong></a>.
    </p>
  </NoteBox>

  <MolecularAnim />

  <h3 class="section-head">Zeitgebers and Entrainment</h3>
  <p>
    Zeitgebers (German: "time-givers") synchronise the internal clock to the
    external world.
    <strong>Light</strong> is the dominant zeitgeber, acting via intrinsically photosensitive
    retinal ganglion cells (ipRGCs) and the retinohypothalamic tract. Non-photic
    zeitgebers include:
  </p>
  <ul>
    <li>
      <strong>Feeding/fasting cycles</strong> — entrain peripheral clocks (liver,
      gut, adipose tissue) via metabolic signals.
    </li>
    <li>
      <strong>Exercise</strong> — acute physical activity can phase-shift the circadian
      system, timing-dependently.
    </li>
    <li>
      <strong>Temperature</strong> — the primary zeitgeber for many organisms; also
      influences mammalian peripheral clocks.
    </li>
    <li>
      <strong>Social cues</strong> — mealtimes, work schedules, and social interactions
      contribute to human circadian timing.
    </li>
  </ul>

  <h3 class="section-head">Why Circadian Biology Matters</h3>
  <h4 class="sub-head">Clinical and Medical Importance</h4>
  <p>
    Circadian disruption — from shift work, jet lag, hospitalisation, or social
    misalignment — has broad health consequences: elevated risk of obesity and
    type 2 diabetes in shift workers; morning peaks in myocardial infarction and
    stroke; associations between shift work and breast, colorectal, and prostate
    cancer (IARC Group 2A carcinogen). In perioperative medicine, surgery and
    ICU care disrupt circadian rhythms through light exposure, fasting,
    sedation, and inflammation, contributing to delirium, immune impairment, and
    delayed recovery.
  </p>

  <h4 class="sub-head">Chronopharmacology and Precision Medicine</h4>
  <p>
    Drug efficacy and toxicity vary with time of administration. Examples:
    evening dosing of ACE inhibitors better suppresses nocturnal blood pressure;
    timed delivery of oxaliplatin and 5-fluorouracil improves chemotherapy
    tolerability; short-acting statins are more effective taken at night when
    hepatic cholesterol synthesis peaks.
  </p>

  <h4 class="sub-head">Research Perspective</h4>
  <p>
    Circadian data are inherently time-structured. Standard statistical methods
    that ignore temporal ordering can give misleading results. This handbook
    provides the foundation to choose the right analysis, estimate parameters
    with appropriate uncertainty, compare rhythms between conditions, and use
    open-source tools reproducibly.
  </p>
  <ChapterExamples chapter="ch1" />
</ChapterSection>
