/**
 * Generates static/nodes.json — a machine-readable manifest of EVERY AnCiR node
 * (table-processes, column-processes, plots), derived from the live registry so
 * it never drifts from the app. Consumed by the Handbook's searchable Node
 * Reference page (which fetches it from raw GitHub main and overlays curated
 * descriptions/maths/references/cross-links).
 *
 * Gated by GEN_MANIFEST so it never runs in the normal suite:
 *   GEN_MANIFEST=1 npx vitest run src/lib/_demos/generateNodeManifest.svelte.test.js
 *
 * Each node entry: { id, displayName, kind, family, description, hideFromPalette,
 *   inputs[], params[], outputs[], demo }. `demo` is the showcase session URL
 *   from the demo gallery index (so the Handbook can deep-link "open in AnCiR").
 */
import { describe, it } from 'vitest';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { appConsts } from '$lib/core/core.svelte.js';
import { loadProcesses } from '$lib/processes/processMap.js';
import { loadPlots } from '$lib/plots/plotMap.js';
import { loadTableProcesses } from '$lib/tableProcesses/tableProcessMap.js';

const OUT = join(process.cwd(), 'static', 'nodes.json');
const INDEX = join(process.cwd(), 'static', 'sessions', 'demos', 'index.json');

// Default-arg keys that are plumbing, not user-facing parameters.
const INTERNAL_KEYS = new Set([
	'out',
	'valid',
	'forcollected',
	'collectedType',
	'tableProcesses',
	'preProcesses',
	'outColIds',
	'storedValueRefs',
	'aggregates'
]);

function paramsFromDefaults(defaults) {
	const out = [];
	if (!defaults || typeof defaults.entries !== 'function') return out;
	for (const [key, def] of defaults.entries()) {
		if (INTERNAL_KEYS.has(key)) continue;
		const val = def && Object.prototype.hasOwnProperty.call(def, 'val') ? def.val : undefined;
		out.push({ name: key, default: val });
	}
	return out;
}

function portList(ports) {
	return (ports ?? []).map((p) => ({
		name: p.name,
		kind: p.artifactKind ?? p.kind ?? 'column',
		cardinality: p.dynamic || p.cardinality === 'many' ? 'many' : 'one',
		...(p.metric ? { metric: true } : {}),
		...(p.dynamicPrefix ? { dynamicPrefix: p.dynamicPrefix } : {})
	}));
}

describe.runIf(process.env.GEN_MANIFEST)('generate node manifest', () => {
	it('writes static/nodes.json from the live registry', { timeout: 120000 }, async () => {
		appConsts.processMap = await loadProcesses();
		appConsts.plotMap = await loadPlots();
		appConsts.tableProcessMap = await loadTableProcesses();

		// node id -> first showcase demo session url
		const idx = JSON.parse(readFileSync(INDEX, 'utf8'));
		const demoByNode = {};
		for (const s of idx.sessions ?? []) {
			for (const sc of s.showcases ?? []) if (!demoByNode[sc]) demoByNode[sc] = s.url;
		}

		const nodes = [];

		const pushTPorProc = (id, entry, kind) => {
			const spec = entry.nodeSpec ?? entry.definition?.nodeSpec ?? {};
			const inputs = portList(spec.inputs);
			// Params are configuration only — drop keys that are wired input ports.
			const inputNames = new Set(inputs.map((i) => i.name));
			const params = paramsFromDefaults(entry.defaults).filter((p) => !inputNames.has(p.name));
			nodes.push({
				id,
				displayName: entry.displayName ?? id,
				kind,
				family: entry.family ?? 'Other',
				description: entry.description ?? '',
				hideFromPalette: !!entry.hideFromPalette,
				inputs,
				params,
				outputs: portList(spec.outputs),
				demo: demoByNode[id] ?? null
			});
		};

		for (const [id, entry] of appConsts.tableProcessMap.entries())
			pushTPorProc(id, entry, 'tableProcess');
		for (const [id, entry] of appConsts.processMap.entries())
			pushTPorProc(id, entry, 'process');

		for (const [id, entry] of appConsts.plotMap.entries()) {
			const def = entry.definition ?? {};
			nodes.push({
				id,
				displayName: entry.displayName ?? def.displayName ?? id,
				kind: 'plot',
				family: entry.family ?? 'Plots',
				description: entry.description ?? '',
				hideFromPalette: !!entry.hideFromPalette,
				inputs: (def.defaultDataInputs ?? entry.defaultInputs ?? []).map((n) => ({
					name: n,
					kind: 'column',
					cardinality: 'many'
				})),
				params: [],
				outputs: [],
				demo: demoByNode[id] ?? null
			});
		}

		nodes.sort((a, b) => a.kind.localeCompare(b.kind) || a.id.localeCompare(b.id));

		const manifest = {
			_comment:
				'Auto-generated by src/lib/_demos/generateNodeManifest.svelte.test.js (GEN_MANIFEST=1). Do not hand-edit. Consumed by the Chronobiology Handbook Node Reference page.',
			generatedFromVersion: appConsts.version ?? null,
			count: nodes.length,
			nodes
		};
		writeFileSync(OUT, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
		// eslint-disable-next-line no-console
		console.log(`wrote ${nodes.length} nodes to static/nodes.json`);
	});
});
