// Per-node explanatory notes embedded into each gallery demo session as an
// on-canvas Note. Keyed by node id (registry key = .svelte file name for
// processes/table-processes, lowercase folder name for plots). Graded: rich
// (method + when-to-use + reference) for analysis/stats nodes; concise +
// practical for basic transforms, sources, and plots.
//
// Consumed by nodeDemoBuilders.addDemoNote() and the curated plot demos in
// generateDemos.svelte.test.js. Regenerate demos after editing:
//   GEN_DEMOS=1 npx vitest run src/lib/_demos/generateDemos.svelte.test.js
export const NODE_NOTES = {
	Add: 'Adds a constant (or another column) to every value in the input column, element-by-element. Use it to apply an offset, shift a baseline, or combine two columns. The demo shows the output column sitting above the input with each value raised by the set amount.',
	AverageProfile:
		"Folds a series onto one period (default 24 h) and reports the mean value in each phase bin with its standard error, giving the 'average day' or mean waveform of the record. Use it to visualise the typical shape and timing of a rhythm across many cycles and to smooth out day-to-day noise before or alongside a parametric fit. In the demo, read each point as the across-days mean at that time-of-day and the error bars as the SEM: a clear peak-and-trough shape marks a robust rhythm, while flat bins with wide bars indicate weak or noisy rhythmicity. Mean-waveform folding (Refinetti et al. 2007).",
	BinnedData:
		'Aggregates time-series values into regular time bins (e.g. 15 min counts into hourly means or sums), choosing the aggregation function per bin. Use it to downsample high-resolution activity or to put irregular samples onto a regular grid before analysis.',
	BlankColumn:
		'Lets you enter data by hand or paste CSV/JSON to create a column (or table) directly on the canvas. Use it for small manual datasets, quick tests, or pasting values from another program.',
	CircadianFunctionIndex:
		'Summarises rest-activity rhythm robustness as a single 0-1 index by combining three nonparametric variables: interdaily stability (IS), intradaily variability (IV) and relative amplitude (RA). Give it a time column and one or more activity columns; it reports CFI plus the raw IS/IV/RA per series. Higher CFI means a more stable, well-consolidated rhythm; useful for comparing individuals or conditions without assuming a sinusoidal shape (Ortiz-Tudela et al. 2010).',
	CollectColumns:
		'Concatenates several columns end-to-end into a single combined column. Use it to pool values from multiple series or segments into one column for a combined summary or plot.',
	ColumnFunctions:
		'Combines several input columns into one result by applying a per-row function across them: element-wise Add, or the row-wise Mean, Min, Max, or Std Dev over the selected columns. Use it to compute, e.g., the average of replicate series or a per-timepoint spread.',
	ColumnSet:
		'Curates a live, named subset of columns by matching their name and/or label against a pattern, and exposes it as a single wire you can plug into any many-input port. The set updates automatically as matching columns are added or removed, so downstream analyses and plots stay in sync without rewiring.',
	Cosinor:
		"Fits a cosine model to a rhythmic series by least squares, returning MESOR (rhythm-adjusted mean), amplitude, acrophase and period, with an F-test / R² and optional permutation p-value. Use it for approximately sinusoidal rhythms when you want interpretable rhythm parameters and a significance test; a fixed period (e.g. 24 h) turns it into linear single/multi-harmonic cosinor, while leaving the period free fits it. In the demo, read the fitted smooth cosine overlaid on the raw points: peak height is the amplitude, the peak's time-of-day is the acrophase, and the horizontal midline is the MESOR. It also emits a residual column per series (observed − fitted) with a \"Plot residuals\" button to check the fit. Method: cosinor rhythmometry (Cornélissen 2014).",
	DoubleLogistic:
		'Fits a double-logistic curve, a rising sigmoid followed by a falling sigmoid, describing a single on-then-off transition (or, in periodic mode, a repeating pulse train). Use it for phenology-style data and activity onsets/offsets where you want to locate and characterise the rise and fall separately (their timing t1, t2 and steepness k1, k2). In the demo, read the ascending limb as the onset transition and the descending limb as the offset; the plateau between them is the active window. It also emits a residual column per series (observed − fitted) with a "Plot residuals" button to check the fit. Double-logistic phenology model (Zhang et al. 2003).',
	EditValue:
		'Overwrites individual cells at specific row positions with values you type in, leaving the rest of the column unchanged. Use it for hand-correcting a few known-bad points without touching the source data. The demo shows the edited positions differing from the input.',
	FilterByOtherCol:
		'Keeps or drops rows according to conditions tested on another column (==, !=, >, <, includes, etc.), so you can subset one column using a grouping or flag column. Combine several conditions to narrow the selection. The demo shows the output retaining only the rows that satisfy the condition.',
	FitFunction:
		'A general curve-fitting node that fits a chosen model, cosinor, rectangular wave, or double logistic, to the series by nonlinear least squares, giving one interface for all three parametric shapes plus a shared permutation test. It reports R² and RMSE, the model coefficients, and a residual column per series (observed − fitted, aligned to the input), with a "Plot residuals" button to scatter them against the input for a fit-diagnostic check (a good fit leaves residuals patternless around zero). Use it when you want to try and compare different waveform models on the same data, or need the permutation-based significance option in one place. In the demo, read the fitted curve over the raw points and compare fit quality (and the permutation p-value) across models to see which shape the data prefer. Nonlinear least-squares model fitting (Marquardt 1963).',
	FormulaColumn:
		"Builds a new column from a formula you write over existing columns and constants (for example (A+B)/2 or log(x)), evaluated row by row. Use it for custom per-row calculations the fixed transforms don't cover — ratios, unit conversions, or combined indices.",
	FrequencyFilter:
		'An FFT-based low-, high-, or band-pass filter for evenly sampled series: it transforms to the frequency domain, zeroes the frequencies outside the chosen band, and transforms back. Cutoffs are given as a fraction of the Nyquist frequency (0 = DC, 1 = fastest resolvable). Use low-pass to smooth, high-pass to remove drift, band-pass to isolate a rhythm. The demo shows the filtered series with the unwanted frequency content removed.\n\nOppenheim & Schafer, Discrete-Time Signal Processing.',
	GroupComparison:
		'Compares a numeric measure across groups defined by a grouping column (or across several y-columns). Auto mode picks a Welch t-test for two groups and a one-way ANOVA for three or more; nonparametric Mann-Whitney U and Kruskal-Wallis are also available, with Tukey-Kramer / Holm-adjusted pairwise post-hoc tests and Jarque-Bera normality and variance-ratio warnings. Outputs the test statistic and p-value as metric ports you can wire onward. Reporting a significant group difference (Kruskal & Wallis 1952).',
	Correlation:
		'Computes every pairwise correlation among the wired columns and reports them one row per pair: var_i, var_j, r, p-value and n. Choose Pearson (linear) or Spearman (rank / monotonic), or leave it on Auto — which uses Spearman if any column fails a Jarque-Bera normality check, so the whole matrix stays on one comparable method. Uses pairwise-complete rows (a missing value drops only that pair-row), and warns on small samples and, for Spearman, on ties. Quick-plot draws the correlation heatmap.',
	DescribeData:
		'Reports summary statistics for each wired column, one row per variable: n, mean, median, standard deviation, min, max, range, first and third quartiles, IQR, skewness and (excess) kurtosis. Skewness and kurtosis use the bias-corrected sample formulae (matching scipy). Quick-plot draws a histogram of each column so you can see the distribution behind the numbers.',
	LogisticRegression:
		'Models a binary outcome (yIN) from one or more predictors (xIN) by iteratively-reweighted least squares. The outcome may be numeric 0/1 or a two-level category (the second level, alphabetically, is taken as the positive class = 1). Reports one row per term: the coefficient (log-odds), standard error, Wald z and p-value, odds ratio and its 95% confidence interval, plus the model log-likelihood, likelihood-ratio test against the null and McFadden pseudo-R². It warns on non-convergence, which usually signals separation (a predictor splits the outcome cleanly). Estimates match statsmodels. Alongside the coefficient table it emits three per-observation columns, outcome, eta (the linear predictor Xβ) and fitted (the predicted probability), so the quick-plot draws fitted probability against the linear predictor (the S-curve, for any number of predictors) with the observed 0/1 outcomes overlaid, and you can rebuild that plot by hand from the columns. Cox 1958.',
	ChiSquared:
		"Pearson's chi-squared test in two modes. Independence: cross-tabulate two categorical columns into a contingency table and test whether the two variables are associated (Yates' continuity correction is applied to 2×2 tables). Goodness-of-fit: take one column and test whether its category counts (or the raw counts, if numeric) depart from a uniform expectation. Reports the statistic, degrees of freedom and p-value, and shows the table in the node. It warns when expected cell counts fall below 5, where the χ² approximation breaks down (prefer Fisher's exact test). Matches scipy (chisquare / chi2_contingency). Pearson 1900.",
	CrossCorrelation:
		"Computes the cross-correlogram of two series (A = the first input, B = the second): the correlation between A and B at each lag from -maxLag to +maxLag, using the overlapping segment only. The peak lag is the delay between the signals — a peak at a positive lag means B leads A by that many samples. Use it to find the phase relationship between two rhythms, or the response delay between a driver and a follower. Choose Pearson (linear) or Spearman (rank); leave max lag at 0 to auto-pick a quarter of the shorter series. Quick-plot draws the correlogram (lag vs r). Chatfield, The Analysis of Time Series.",
	NormalityTest:
		"Tests whether each wired column is drawn from a normal distribution, one row per variable: the test statistic, its p-value, n, and a yes/no verdict at your chosen alpha. Shapiro-Wilk (the default, and the most powerful test; valid for 3 ≤ n ≤ 5000) is recommended; D'Agostino-Pearson (an omnibus skewness + kurtosis K² test, n ≥ 8, better for very large samples) and Jarque-Bera are also available. A small p-value means the data depart from normality, so a rank / non-parametric method is safer downstream. All three match scipy (shapiro / normaltest / jarque_bera). Shapiro & Wilk 1965; Royston 1995.",
	Interpolate:
		'Fills gaps or resamples a series onto a regular time grid using linear, nearest-neighbour, or natural cubic-spline interpolation. Use it to repair missing values or to make unevenly sampled data evenly spaced before methods that assume regular sampling (e.g. FFT).',
	LongToWide:
		'Pivots a long/tidy table (a category column, a time column and a value column) into wide format, producing one value-column per category sharing a common time column. Use it to turn a stacked per-subject table into side-by-side series ready for plotting or per-series analysis.',
	MovingAnalysis:
		"Slides a window along the record and runs a chosen analysis (periodogram, cosinor, FFT, correlogram, or a waveform fit) in each window, producing a time-course of the result. Use it to track how a rhythm parameter changes over the recording, for example period drift during a free run or amplitude decay after a lesion. In the demo, read the output as a trajectory: each point is one window's estimate (period, amplitude, or power) plotted against the window's centre time, so a rising or falling line shows the rhythm evolving. Sliding-window periodogram/cosinor analysis (Refinetti et al. 2007).",
	Multiply:
		'Multiplies every value in the input column by a constant (or another column), element-by-element. Use it for unit conversions, scaling, or rescaling a signal. The demo shows the output column scaled relative to the input.',
	NonparametricRA:
		'Computes the standard nonparametric rest-activity variables without assuming any waveform: interdaily stability (IS, day-to-day reproducibility of the 24 h pattern), intradaily variability (IV, fragmentation), relative amplitude (RA), and the most-active 10 h and least-active 5 h windows (M10, L5) with their onset times. Use it for actigraphy or other activity records that are non-sinusoidal, where cosinor amplitude/phase are ill-defined. The demo shows the folded average-day profile: the flat high plateau is M10, the deep trough is L5, and RA near 1 means a strong, consolidated rhythm while low IS or high IV signals a weak or fragmented one. Nonparametric methods after Van Someren et al. (1999); IS/IV originate in Witting et al. (1990).',
	OutlierRemoval:
		"Flags extreme values and replaces them with blanks, using either a z-score threshold (default |z| > 3) or Tukey's IQR fence (Q1 - k·IQR, Q3 + k·IQR, default k = 1.5). Use it to stop a handful of spikes dominating fits and spectra. The demo shows the flagged points removed while the rest of the series is preserved.\n\nTukey, J.W. (1977) Exploratory Data Analysis.",
	Random:
		'Generates a column of pseudo-random values from a uniform, Gaussian, or exponential distribution, scaled by an offset and multiplier, with a fixed seed for reproducibility. Use it to add controlled noise or to create random test data.',
	RayleighTest:
		"Circular-statistics tests for phase/angle columns (radians, degrees, or clock-hours on a chosen period). The Rayleigh test always runs: for each column it asks whether the phases (e.g. acrophases, activity-onset times) point in a preferred direction rather than scattering uniformly, reporting the mean resultant length R (0 = dispersed, 1 = tightly clustered), Rayleigh's z = nR², a p-value, and an acrophase (Batschelet 1981). Wiring an optional time column — numeric hours or an actual timestamp, folded modulo the period to a clock phase — switches every column to an amplitude-weighted mode: each value weights its own measurement time's angle, giving an amplitude-weighted mean resultant vector and acrophase (the weighted mean time-of-peak) instead of treating the column as a set of raw angles; the unit setting is then ignored. An optional Watson-Williams test (toggle it on, like the boxplot's pairwise comparisons) adds the circular analogue of one-way ANOVA across the columns (each a group of raw angles), reporting an F statistic and p-value for whether the groups share a common mean direction; it assumes reasonably concentrated, similarly-dispersed samples and applies a von Mises concentration correction (Watson & Williams 1956) — it only applies to untimed columns, since it compares discrete event angles, not a continuous weighted rhythm. In the demo the two angle columns each cluster tightly (small Rayleigh p) but around different mean directions, so the Watson-Williams test is significant.",
	RectangularWave:
		"Fits a smooth rectangular (square) wave with an adjustable duty cycle to the series, capturing on/off activity rhythms that a sinusoid fits poorly. The model is a tanh-approximated square wave whose duty cycle sets the fraction of each cycle spent 'on'; period, phase, sharpness (kappa) and duty cycle can be fixed or fitted. Use it for clearly bimodal activity (e.g. nocturnal animals switching between rest and activity) where you want an explicit active-phase width. In the demo, read the flat high plateau as the active phase, the flat low level as rest, and the plateau width as the duty cycle. It also emits a residual column per series (observed − fitted) with a \"Plot residuals\" button to check the fit. Nonlinear least-squares waveform fitting (Marquardt 1963).",
	RemoveTrend:
		"Fits a trend (linear, polynomial, exponential, or logarithmic) against a chosen x-column and subtracts it, leaving the residual (detrended) signal. Use it to remove baseline drift or sensor decay before rhythm analysis so a slow trend doesn't masquerade as a long period. An optional sliding window detrends locally. The demo shows the drifting input flattened around zero.",
	RhythmicityAnalysis:
		'Runs a spectral / periodicity analysis over the series and reports the dominant period and its strength. Choose the method: a periodogram (Lomb-Scargle by default, which tolerates uneven sampling and gaps; chi-squared or Enright also available), a Fourier transform (FFT), or an autocorrelogram. Use it to detect whether a rhythm is present and to estimate its period without assuming a waveform. In the demo, read the output spectrum: a clear peak marks the dominant period, its height is the power/magnitude, and (for chi-squared) the significance line shows whether it exceeds chance. Lomb-Scargle periodogram (Lomb 1976; Scargle 1982).',
	SequenceColumn:
		'Creates a regular numeric or time sequence from a start, step, and count (or end). Use it to build an index or an evenly spaced time axis to pair with generated or pasted values.',
	SimulatedData:
		'Generates a synthetic time-series from one or more cosine sections (each with its own period, phase, amplitude, and optional additive or multiplicative noise) at a chosen sampling interval. Use it to create test data with a known ground truth for learning, demonstrating, or validating the analysis nodes.',
	SmoothedData:
		'Smooths a series to suppress noise while keeping the underlying shape. Choose Whittaker-Eilers (penalised least squares; λ sets stiffness), Savitzky-Golay (local polynomial, preserves peak height/width), LOESS (locally weighted regression; bandwidth sets span), or a moving average. Use a light hand: over-smoothing flattens real amplitude. It also emits a residual column per series (raw − smoothed) with a "Plot residuals" button, so you can see exactly what was removed and check you have not smoothed away real signal. The demo overlays the smoothed curve on the noisy input.\n\nSavitzky & Golay (1964); Cleveland (1979, LOESS); Eilers (2003, Whittaker).',
	Sort: 'Reorders rows by a chosen key column, ascending or descending, keeping the selected columns aligned. Use it to order data by time or magnitude before plotting or before methods that assume monotonic time.',
	Threshold:
		'Turns a continuous column into a 0/1 (binary) column at a cutoff you set, choosing which side of the threshold counts as 1 (>, ≥, <, ≤). Missing values stay missing. The usual use is making a binary outcome for logistic regression, but it also flags events (e.g. "activity above baseline").',
	Split:
		'Cuts a time-series into consecutive segments at the split times you specify, keeping the chosen columns aligned. Use it to separate, e.g., an entrainment stage from a free-run stage, or successive days, before analysing each part on its own.',
	StoredValueGroup:
		'Gathers scalar results you have stored from various analyses (e.g. periods, amplitudes, CFI values) and organises them into labelled groups, emitting a category column and a value column. Use it to assemble stored metrics into a tidy table for group comparison or plotting.',
	Sub: 'Finds every occurrence of one specific value and replaces it with another, leaving all other values untouched. Its main use is recoding sentinel/missing-data codes (e.g. swapping -999 for a blank) before analysis. The demo shows the target value replaced throughout the column.',
	TrendFit:
		'Fits and stores a simple trend, linear, polynomial, exponential or logarithmic, to the series by least squares, reporting the fitted curve, R² and RMSE plus the coefficients, and a residual column per series (observed − fitted) with a "Plot residuals" button for a fit-diagnostic scatter. Use it to describe or remove a slow trend (baseline drift, growth or decay) before rhythm analysis, since detrending prevents low-frequency drift from contaminating periodograms and cosinor fits. In the demo, read the smooth fitted line through the data: how closely it hugs the points is summarised by R² (near 1 = tight fit) and RMSE (residual scatter). Detrending for rhythm analysis (Refinetti et al. 2007).',
	WideToLong:
		'Pivots several side-by-side value columns into long/tidy format: a single time, category, and value column. Use it to stack multiple series into one table for grouped statistics or long-format export.',
	actogram:
		'The classic chronobiology display: activity plotted against time of day, one row per day and double-plotted (each day shown twice, side by side) so rhythms crossing midnight stay visible and drift reads as a diagonal band. Use it to eyeball period, phase, and entrainment. The demo shows a clear daily activity band.\n\nRefinetti, Cornélissen & Halberg (2007), Biol. Rhythm Res.',
	boxplot:
		'Summarises the distribution of a y-column within each group defined by an x-column: the box spans the interquartile range, the line is the median, and whiskers reach the data extent (points beyond are outliers). Use it to compare spread and central tendency across days, conditions, or subjects. The demo shows one box per group.',
	circularphase:
		"Plots one or more phase/angle columns (e.g. acrophases, activity onsets) as points around a clock face on an adjustable period, each column a coloured group with its Rayleigh mean-resultant vector — the arrow's length is R (0 = dispersed, 1 = tightly clustered) (Batschelet 1981). Wiring an optional time column to a series turns it into a value-radius clock plot instead: each row is placed at its time-of-day with radius proportional to its value, and the vector becomes an amplitude-weighted acrophase. Toggle rose wedges for a circular histogram of an untimed group, or the Watson-Williams test (the circular analogue of one-way ANOVA) to ask whether untimed groups share a common mean direction (Watson & Williams 1956) — timed series sit outside that comparison, since WW compares discrete event angles, not a continuous weighted rhythm. The demo shows both modes: two untimed onset-phase groups (near 7 h and 19 h) with a significant Watson-Williams test, plus a timed activity series rendered as a value-radius clock.",
	correlogram:
		'Plots the autocorrelation of a series against lag (or the cross-correlation between two series). A rhythmic signal produces a decaying wave whose first strong positive peak away from zero lag estimates the period. Use it as a robust complement to the periodogram. See the Correlograms chapter.',
	dataview:
		'A lightweight raw-data viewer for the columns you select, letting you scroll through the actual values behind the graphs. Use it to inspect imported data, spot gaps or coding issues, and confirm columns are wired correctly. It shows the underlying rows rather than any computed summary.',
	fft: 'Fourier analysis decomposes an evenly sampled series into sinusoidal components and plots amplitude (spectral power) against frequency; a peak at a given frequency corresponds to a rhythm of period 1/frequency. Use it to identify dominant frequencies and harmonics. See the Fourier Analysis chapter.',
	histogram:
		"Bins a single column's values and draws the count in each bin, showing the shape of its distribution (centre, spread, skew, modes, outliers). Use it to check whether data are roughly normal before choosing a statistical test. The demo shows an approximately bell-shaped distribution.",
	meansem:
		"Overlays each group's mean as a marker with whiskers showing ± one standard error of the mean (SEM = s/√n), grouped by the x-column. Use it to compare average levels across conditions or time bins while showing the precision of each mean. The demo shows per-group means with error bars.",
	normalize:
		"Rescales a column so different series are comparable. Z-score centres to mean 0 / SD 1; Min-Max rescales into a chosen range; Robust uses median and MAD (outlier-resistant); Unit-vector scales by the column's magnitude. The demo shows the input rescaled onto the new scale with its shape preserved. Choose z-score/robust when comparing rhythms of different amplitudes.",
	periodogram:
		"Scans a range of candidate periods and plots spectral power against period, with a significance threshold; the tallest peak crossing the line estimates the dominant rhythm's period. Methods include Lomb-Scargle (handles uneven sampling/gaps) and the chi-squared (Sokolove-Bushell) periodogram. Use it to quantify period from a time-series. See the Periodograms chapter for details.",
	scatterplot:
		'Plots one column against another as points, most often a value against time to view a raw time-series. Wire x (e.g. time) and y (values); multiple y-columns overlay as separate series. Supports zoom/pan and an optional facet mode (one small plot per series). Use it as your first look at the data before any analysis.',
	tableplot:
		"Renders selected columns (or their summary statistics) as a plain data table for inspection and export. Use it to read exact values, sanity-check a transform's output, or present computed metrics. The demo shows the chosen columns laid out in rows and columns.",

	// --- Workflow templates (canonical multi-node pipelines from the
	// chronobiology literature). Keyed `workflow-<id>`, consumed by the
	// WORKFLOWS section of generateDemos.svelte.test.js. ---
	'workflow-rest-activity':
		"WORKFLOW: actigraphy rest-activity profile. The consensus way to characterise a rest-activity record without assuming a sine shape (van Someren / Witting; Gonçalves et al. 2015). Step 1 — each group's subjects go into one Nonparametric RA node, which reports the four canonical variables per subject: interdaily stability IS (day-to-day consistency with the 24 h zeitgeber, →1 = stable), intradaily variability IV (fragmentation: transitions between rest and activity, →0 = consolidated), and M10/L5 (mean activity of the most-active 10 h and least-active 5 h) from which relative amplitude RA = (M10-L5)/(M10+L5) derives. Because the scalar metric ports report ONE VALUE PER Y INPUT, each port emits a whole column — that group's distribution. Step 2 — a Cosinor node on the same subjects adds the model-based view (amplitude, acrophase); combining nonparametric + model-based is the recommended pairing (Fossion et al. 2017). Step 3 — the two RA columns feed a Compare groups node, which treats each column as one group and tests whether rhythm robustness differs. The actogram shows a representative subject from each group so the numbers have a picture: the consolidated subject shows a solid daily block, the fragmented one is broken up. NOTE: this demo's data is already at the 1 h analysis epoch; logger data sampled finer (e.g. 30 s or 1 min) should be binned to the analysis epoch with a Bin node first, and `epochHours` set to match.",
	'workflow-free-running':
		'WORKFLOW: free-running period. How to measure the endogenous period (tau) of a rhythm running without a zeitgeber (e.g. constant darkness). Step 1 — the actogram is the diagnostic view: it is double-plotted (two cycles side by side) against a 24 h grid, so a rhythm whose tau differs from 24 h shows as a band DRIFTING steadily across days rather than sitting vertical. Drift to the right = tau > 24 h; to the left = tau < 24 h. Step 2 — the periodogram estimates tau numerically: this demo uses Lomb-Scargle, which handles unevenly sampled data and is the recommended default. Step 3 — the Rhythmicity Analysis node reports the peak period as a wireable number (shown in the table), so it can feed a group comparison. IMPORTANT — method choice: avoid the chi-square (Sokolove-Bushell) periodogram as a first choice; it systematically UNDERESTIMATES period in a way that depends on the true period and record length, and Lomb-Scargle or a padded FFT are more accurate (Tackenberg & Hughey 2021). Record length and noise matter far more than sampling frequency: ~5+ days is a reasonable minimum, and a baseline trend should be detrended before estimating period (Zielinski et al. 2014).',
	'workflow-phase-groups':
		"WORKFLOW: group phase comparison. The canonical way to ask 'do these two groups peak at different times of day?'. Step 1 — each group's subjects are fitted by one Cosinor node; because the scalar metric ports report ONE VALUE PER Y INPUT, the node's `acrophase` port emits a whole column of per-subject peak times (h), i.e. that group's phase distribution. Step 2 — both acrophase columns are wired into the circular phase plot, placing each subject on a 24 h clock with its group's Rayleigh mean-resultant vector (arrow length R: 0 = dispersed, 1 = tightly clustered). Step 3 — the same two columns feed the Rayleigh test node, which always reports R, z and a p-value per group (is there a preferred direction at all?) and, with the Watson-Williams toggle on, additionally reports F and a p-value for whether the groups share a common mean direction — the circular analogue of one-way ANOVA. Read it as: significant Rayleigh = each group is genuinely clustered; significant Watson-Williams = the groups peak at different phases. Swap the Cosinor node for a periodogram peak or an actogram onset marker to phase-type the same way (Batschelet 1981; Watson & Williams 1956; Cornelissen 2014).",

	// --- General-statistics workflow templates (discipline-neutral). Same arc as
	// the chronobiology ones: explore → check assumptions → test/model → visualise
	// → interpret. Keyed `workflow-stats-<id>`. ---
	'workflow-stats-eda':
		"WORKFLOW: exploratory data analysis (the first look). Before any test, get to know the data. Step 1 — Describe Data reports n, centre (mean/median), spread (sd, IQR) and shape (skewness, (excess) kurtosis) for every variable; a median far from the mean, or a large skew, flags an asymmetric distribution. Step 2 — the faceted histograms show each distribution directly (one small-multiple per variable): look for skew, bimodality, gaps and outliers. Step 3 — a normality test screens each variable (Shapiro-Wilk by default); a small p-value means non-normal, which steers you toward rank / non-parametric methods later. Step 4 — the correlation heatmap and pairs plot map the pairwise relationships (scatter + linear fit above the diagonal, distributions on it) so you can see which variables move together BEFORE modelling. Read it as reconnaissance, not inference: this pass tells you which tests are appropriate and where the data-quality problems are. Tukey, Exploratory Data Analysis (1977).",
	'workflow-stats-two-group':
		"WORKFLOW: compare two groups. The most common inferential question — is group A different from group B? Compare groups on 'auto' inspects each group for normality (Jarque-Bera) and equal variance and PICKS the test for you: a Welch t-test when both groups look roughly normal, a Mann-Whitney U (rank) test when they do not; it surfaces the choice and any assumption warnings so the decision is visible, not hidden. Read the output in order: (1) which test fired and why, (2) the p-value against your α, (3) the DIRECTION and size of the difference — the boxplot shows the medians, spread and any outliers, and the significance bar marks a detected difference. A significant p tells you the groups differ; the boxplot tells you by how much and whether it matters. Student (1908); Mann & Whitney (1947); Welch (1947).",
	'workflow-stats-anova':
		"WORKFLOW: compare several groups (one-way ANOVA). With three or more conditions you cannot just run many t-tests — that inflates the false-positive rate. Compare groups on 'auto' runs the omnibus test first (one-way ANOVA when the groups look normal, Kruskal-Wallis otherwise): a single test of 'do ANY of the groups differ?'. ONLY if that omnibus p is significant do you read the post-hoc pairwise grid (Tukey-Kramer / Holm-adjusted), which controls the family-wise error across the comparisons and tells you WHICH pairs differ. The mean ± SEM plot shows the group means and their precision; the boxplot with significance bars shows the full distributions and the significant pairs. Read top-down: omnibus → (if significant) post-hoc → effect direction. Fisher (1925); Tukey (1949); Kruskal & Wallis (1952).",
	'workflow-stats-correlation':
		"WORKFLOW: correlation & relationships. Which variables move together, and how? Correlation computes every pairwise coefficient among the wired columns; on 'auto' it uses Spearman (rank / monotonic) if any column fails a normality check, else Pearson (linear), so the whole matrix stays on one comparable method. Read three things: (1) STRENGTH and DIRECTION from the heatmap — deep blue/red = strong negative/positive, pale = weak; (2) LINEAR vs MONOTONIC — the pairs plot's scatterplots show whether a relationship is a straight line (Pearson-appropriate) or a curved-but-monotonic trend (where Spearman is larger and more honest); (3) MULTICOLLINEARITY — several predictors strongly correlated with each other is a warning for any regression that uses them together. Correlation is not causation, and a near-zero coefficient only rules out a MONOTONIC relationship, not any relationship. Pearson (1895); Spearman (1904).",
	'workflow-stats-regression':
		"WORKFLOW: linear regression + residual diagnostics. Predict a continuous Y from X, then check the model is trustworthy — the second half is the part people skip. Step 1 — Fit Trend Curves (linear) reports the slope, intercept and R² (fraction of variance explained) and overlays the fitted line on the data. Step 2 — the DIAGNOSTIC: the residuals (observed − fitted) are plotted against X. A good fit leaves them scattered structurelessly around zero; a funnel shape means non-constant variance (heteroscedasticity), and a curve means the straight-line model is wrong — BOTH can hide behind a high R². Step 3 — a normality test on the residuals checks the assumption behind the p-values and confidence intervals. The lesson: never report R² without looking at the residuals. To model a curved relationship, switch the Fit Trend model to polynomial/exponential and re-check the residuals. Galton (1886); Anscombe (1973).",
	'workflow-stats-logistic':
		"WORKFLOW: logistic regression (binary outcome). When the outcome is yes/no rather than a number, linear regression is the wrong tool — logistic regression models the PROBABILITY of the outcome. Read the coefficient table as ODDS RATIOS with 95% confidence intervals: an odds ratio above 1 means the predictor raises the odds of the outcome, below 1 lowers them, and a CI that does not cross 1 is 'significant' (matching the Wald p-value). The model-level fit is the likelihood-ratio test (does the model beat the intercept-only null?) and McFadden's pseudo-R². The fit plot shows the predicted probability against the linear predictor η = Xβ — the classic S-curve, which generalises to ANY number of predictors — with the observed 0/1 outcomes overlaid so you can see the separation. Watch for a non-convergence warning: it usually signals separation (a predictor splits the outcome perfectly), which makes the estimates unreliable. Cox (1958); Hosmer & Lemeshow (2000).",
	'workflow-stats-chi-square':
		"WORKFLOW: categorical association (chi-square). When both variables are categories (not numbers), the question 'are they related?' is answered by the chi-squared test of independence. It cross-tabulates the two columns into a contingency table of observed counts, computes the counts you'd EXPECT if the variables were independent, and measures the gap: a large χ² (small p) means the observed pattern departs from independence — the variables are associated. Read the statistic, the degrees of freedom ((rows−1)×(cols−1)) and the p-value, then look at the table to see WHERE the association is (which cells are over- or under-represented). Yates' continuity correction is applied to 2×2 tables. Crucial caveat: the χ² approximation is unreliable when any EXPECTED count is below 5 (the node warns) — with small samples use Fisher's exact test instead. The test shows association, not direction or causation. Pearson (1900); Fisher (1922)."
};
