/**
 * Build the "export session as Python" SIDECAR.
 *
 * (No shebang: vite.config.js imports this, and esbuild inlines the config's imports into
 * one file, where a `#!` line partway through is a syntax error. Run it as `node
 * scripts/buildPythonExport.mjs`.)
 *
 * Why a sidecar at all
 * -------------------
 * AnCiR ships as ONE file: `bundleStrategy: 'inline'` plus `assetsInlineLimit: Infinity`
 * fold every module and asset into build/index.html, which is the only build output the
 * repo tracks and the routine FTP deploy publishes. That is deliberate — but it also means
 * a lazy `import('$tools/ancir_runtime.py?raw')` does NOT stay lazy: the 198 KB Python
 * runtime was being inlined into index.html and paid for by every visitor, whether or not
 * they ever exported Python. It was ~7% of the shipped page (raw AND gzipped) for a
 * feature marked experimental.
 *
 * Anything under static/ is copied verbatim by adapter-static instead of being bundled, so
 * emitting the exporter there takes it out of index.html while keeping it one fetch away.
 *
 * What it emits
 * -------------
 * static/ancir-python-export.js — a dependency-free ES module exporting
 * `buildPythonScript(session)`, which is `sessionToPython` with the runtime already baked
 * in. It is assembled from, not a copy of, the canonical sources:
 *
 *   src/lib/utils/pythonExport.js  the generator (linted, unit-tested, single source of truth)
 *   tools/ancir_runtime.py         the runtime the generated script embeds
 *
 * Verbatim inclusion of the generator is only safe because it imports nothing and exports
 * exactly one symbol; `assertSelfContained` below enforces both, so the day someone adds an
 * import to pythonExport.js this fails loudly at build time instead of shipping a sidecar
 * that throws on the user's first click.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export const GENERATOR_SRC = 'src/lib/utils/pythonExport.js';
export const RUNTIME_SRC = 'tools/ancir_runtime.py';
export const SIDECAR_OUT = 'static/ancir-python-export.js';

/**
 * The generator is inlined into the sidecar as-is, which is sound only while it stays
 * dependency-free. Rather than trust that, check it: an added `import` would produce a
 * module the browser cannot resolve from static/, and the failure would surface as a
 * broken feature rather than a broken build.
 */
export function assertSelfContained(source, path = GENERATOR_SRC) {
	// Import/export keywords appear inside the Python template literals too ("import numpy
	// as np"), so anchor to the start of a line and require JS syntax after the keyword.
	const jsImport = /^\s*import\s+(?:[\w*{][^\n]*\sfrom\s+)?['"]/m;
	if (jsImport.test(source)) {
		throw new Error(
			`${path} now has a JS import, so it can no longer be inlined verbatim into ` +
				`${SIDECAR_OUT}. Either drop the import or teach this script to bundle.`
		);
	}
	const exports = [...source.matchAll(/^\s*export\s+(?:default\s+)?(?:function|const|let|class)\s+(\w+)/gm)]
		.map((m) => m[1]);
	if (!exports.includes('sessionToPython')) {
		throw new Error(`${path} no longer exports sessionToPython; ${SIDECAR_OUT} would be empty.`);
	}
	return exports;
}

/** Assemble the sidecar text. Pure, so the tests can exercise it without touching disk. */
export function buildSidecar(generatorSource, runtimeSource) {
	assertSelfContained(generatorSource);
	return `// GENERATED by scripts/buildPythonExport.mjs — do not edit.
// Source of truth: ${GENERATOR_SRC} + ${RUNTIME_SRC}
//
// Kept OUT of index.html on purpose: the app inlines its whole bundle into one file, and
// the Python runtime below is ~198 KB that only matters to someone who exports Python.
// The main page loads this on demand and degrades with a clear message if it is absent.

${generatorSource}

/** The canonical runtime (${RUNTIME_SRC}), embedded so the sidecar needs no second fetch. */
const ANCIR_PYTHON_RUNTIME = ${JSON.stringify(runtimeSource)};

/** Convert a session to a runnable, self-contained Python script. */
export function buildPythonScript(session) {
	return sessionToPython(session, ANCIR_PYTHON_RUNTIME);
}
`;
}

/** Write the sidecar. Returns {path, bytes, changed} — `changed` keeps dev rebuilds quiet. */
export function writeSidecar(root = ROOT) {
	const generator = readFileSync(join(root, GENERATOR_SRC), 'utf8');
	const runtime = readFileSync(join(root, RUNTIME_SRC), 'utf8');
	const text = buildSidecar(generator, runtime);
	const out = join(root, SIDECAR_OUT);

	let previous = null;
	try {
		previous = readFileSync(out, 'utf8');
	} catch {
		// Absent on a clean checkout; that is the normal first-build path, not an error.
	}
	if (previous !== text) {
		mkdirSync(dirname(out), { recursive: true });
		writeFileSync(out, text, 'utf8');
	}
	return {
		path: relative(root, out),
		bytes: Buffer.byteLength(text),
		changed: previous !== text
	};
}

// Runnable on its own (`node scripts/buildPythonExport.mjs`) as well as from the Vite plugin.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
	const { path, bytes } = writeSidecar();
	console.log(`Wrote ${path} (${(bytes / 1024).toFixed(1)} KB)`);
}
