/**
 * Build the "export session as R" SIDECAR.
 *
 * Same shape and same reasoning as scripts/buildPythonExport.mjs: AnCiR ships as one
 * inlined index.html, so a lazy import does not stay lazy, and a ~90 KB R runtime nobody
 * asked for should not be in every visitor's first paint. Anything under static/ is copied
 * verbatim by adapter-static instead of bundled.
 *
 * (No shebang: vite.config.js imports this and esbuild inlines the config's imports into one
 * file, where a `#!` line partway through is a syntax error. Run it as
 * `node scripts/buildRExport.mjs`.)
 *
 * Emits static/ancir-r-export.js, a dependency-free ES module exporting
 * `buildRScript(session)` — `sessionToR` with the runtime already baked in.
 *
 * Sources, neither of which this script may reinterpret:
 *   src/lib/utils/rExport.js   the generator (linted, unit-tested, single source of truth)
 *   tools/ancir_runtime.R      the runtime the generated script embeds
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export const GENERATOR_SRC = 'src/lib/utils/rExport.js';
export const RUNTIME_SRC = 'tools/ancir_runtime.R';
export const SIDECAR_OUT = 'static/ancir-r-export.js';

/**
 * The generator is inlined verbatim, which is sound only while it imports nothing. Checked
 * rather than trusted: an added import would produce a module the browser cannot resolve
 * from static/, and the failure would surface as a broken feature rather than a broken build.
 */
export function assertSelfContained(source, path = GENERATOR_SRC) {
	// Anchored to the start of a line and requiring JS syntax after the keyword, so the word
	// "import" inside the R template literals cannot trip it.
	const jsImport = /^\s*import\s+(?:[\w*{][^\n]*\sfrom\s+)?['"]/m;
	if (jsImport.test(source)) {
		throw new Error(
			`${path} now has a JS import, so it can no longer be inlined verbatim into ` +
				`${SIDECAR_OUT}. Either drop the import or teach this script to bundle.`
		);
	}
	const exports = [
		...source.matchAll(/^\s*export\s+(?:default\s+)?(?:function|const|let|class)\s+(\w+)/gm)
	].map((m) => m[1]);
	for (const name of ['sessionToR', 'sessionToRFiles']) {
		if (!exports.includes(name)) {
			throw new Error(`${path} no longer exports ${name}; ${SIDECAR_OUT} would be broken.`);
		}
	}
	return exports;
}

/** Assemble the sidecar text. Pure, so the tests can exercise it without touching disk. */
export function buildSidecar(generatorSource, runtimeSource, appVersion = 'dev') {
	assertSelfContained(generatorSource);
	return `// GENERATED by scripts/buildRExport.mjs — do not edit.
// Source of truth: ${GENERATOR_SRC} + ${RUNTIME_SRC}
//
// Kept OUT of index.html on purpose: the app inlines its whole bundle into one file, and the
// R runtime below only matters to someone who exports R. The main page loads this on demand
// and degrades with a clear message if it is absent.

${generatorSource}

/** The canonical runtime (${RUNTIME_SRC}), embedded so the sidecar needs no second fetch. */
const ANCIR_R_RUNTIME = ${JSON.stringify(runtimeSource)};

/** The AnCiR version this sidecar was built by — stamped into split-mode helper files. */
const ANCIR_APP_VERSION = ${JSON.stringify(appVersion)};

/** Convert a session to a runnable, self-contained R script. */
export function buildRScript(session) {
	return sessionToR(session, ANCIR_R_RUNTIME);
}

/** Convert a session to R export files ({split, dataAsCsv} options). */
export function buildRExportFiles(session, opts) {
	return sessionToRFiles(session, ANCIR_R_RUNTIME, {
		version: ANCIR_APP_VERSION,
		...(opts ?? {})
	});
}
`;
}

/** The app version, read from package.json — the version stamp for helper files. */
export function readAppVersion(root = ROOT) {
	try {
		const version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version;
		return typeof version === 'string' && version ? version : 'dev';
	} catch {
		return 'dev';
	}
}

/** Write the sidecar. Returns {path, bytes, changed} — `changed` keeps dev rebuilds quiet. */
export function writeSidecar(root = ROOT) {
	const generator = readFileSync(join(root, GENERATOR_SRC), 'utf8');
	const runtime = readFileSync(join(root, RUNTIME_SRC), 'utf8');
	const text = buildSidecar(generator, runtime, readAppVersion(root));
	const out = join(root, SIDECAR_OUT);

	let previous = null;
	try {
		previous = readFileSync(out, 'utf8');
	} catch {
		// Absent on a clean checkout; that is the normal first-build path, not an error.
	}
	if (previous !== text) {
		mkdirSync(dirname(out), { recursive: true });
		writeFileSync(out, text, 'utf8');
	}
	return {
		path: relative(root, out),
		bytes: Buffer.byteLength(text),
		changed: previous !== text
	};
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
	const { path, bytes } = writeSidecar();
	console.log(`Wrote ${path} (${(bytes / 1024).toFixed(1)} KB)`);
}
