#!/usr/bin/env python3
"""
ancir_to_python.py — AnCiR session.json to stand-alone Python script.

Usage:
    python ancir_to_python.py session.json -o analysis.py
    python analysis.py             # runs the full pipeline

The generated script embeds the AnCiR runtime (the implemented column
processes and all 22 JS table processes), the session's raw data, the
column metadata
with its process stack, and one block per table with its table-process
chain executed in order. Output columns from each table are saved as CSV
files alongside the script.
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from pathlib import Path


HERE = Path(__file__).parent
RUNTIME_PATH = HERE / "ancir_runtime.py"


HEADER = '''#!/usr/bin/env python3
"""Generated by ancir_to_python.py — do not edit by hand."""
from __future__ import annotations
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import optimize as sp_optimize, stats as sp_stats
'''


FOOTER_RUN = '''

# ----------------------------------------------------------------------
# Pipeline
# ----------------------------------------------------------------------

def main():
    columns_index = {}
    for cid, meta in COLUMN_META.items():
        col = Column(
            id=cid,
            name=meta["name"],
            type=meta["type"],
            data=meta.get("data"),
            raw_data=RAW_DATA,
            time_format=meta.get("timeFormat"),
            bin_width=meta.get("binWidth", 1.0),
            compression=meta.get("compression"),
            ref_id=meta.get("refId"),
            columns_index=None,  # set after all are built
            processes=meta.get("processes", []),
        )
        columns_index[cid] = col
    # link cross-column references
    for c in columns_index.values():
        c.columns_index = columns_index

    stored = dict(STORED_VALUES)

    output_dir = Path(__file__).with_suffix("").name + "_output"
    out_path = Path(output_dir)
    out_path.mkdir(exist_ok=True)

    # Save column outputs (after processes applied)
    rows = {}
    for c in columns_index.values():
        rows[c.name] = c.get_data()
    # pad to equal length for DataFrame
    max_len = max((len(v) for v in rows.values()), default=0)
    for k in rows:
        rows[k] = list(rows[k]) + [None] * (max_len - len(rows[k]))
    df_cols = pd.DataFrame(rows)
    df_cols.to_csv(out_path / "columns.csv", index=False)
    print(f"[ancir] wrote {out_path / 'columns.csv'} ({len(df_cols)} rows, {len(df_cols.columns)} cols)")

    # Run table processes: each writes into RAW_DATA[out_id], so column data is
    # updated in-place. After running, dump every column to CSV. Free table-
    # process nodes are stored in creation order (oldest first), which respects
    # dependencies, so they run in array order.
    #
    # By default the runtime is strict (STRICT_PROCESSES = True): an unknown
    # process raises UnsupportedProcessError and aborts here rather than
    # silently producing wrong output. Set STRICT_PROCESSES = False above to
    # continue past unknown processes (output WILL be wrong); they are then
    # listed in the summary below.
    for tp in TABLE_PROCESSES:
        ok = run_table_process(tp["name"], tp["args"],
                               columns_index, RAW_DATA, stored)
        print(f"[ancir]   {tp['name']}: {'ok' if ok else 'skipped/empty'}")

    # Dump all columns again (now reflecting TP outputs)
    rows = {}
    for c in columns_index.values():
        rows[c.name] = c.get_data()
    max_len = max((len(v) for v in rows.values()), default=0)
    for k in rows:
        rows[k] = list(rows[k]) + [None] * (max_len - len(rows[k]))
    df_final = pd.DataFrame(rows)
    df_final.to_csv(out_path / "columns_after_tables.csv", index=False)
    print(f"[ancir] wrote {out_path / 'columns_after_tables.csv'} "
          f"({len(df_final)} rows, {len(df_final.columns)} cols)")

    # Render plots (PNG) and export their computed data (CSV). The CSVs mirror
    # the app's "Show/Save data" for calculating plots (periodogram, FFT,
    # correlogram, actogram) — the numbers the plot derives, not the raw input.
    if PLOTS:
        render_plots(PLOTS, columns_index, out_path)
        export_plot_data(PLOTS, columns_index, out_path)

    # Loud summary of any unsupported processes (only reachable when
    # STRICT_PROCESSES was set to False; strict mode aborts earlier).
    if UNSUPPORTED_PROCESSES:
        print("\\n" + "=" * 70)
        print("WARNING: the following processes are NOT implemented by the "
              "runtime.\\nTheir outputs are WRONG (the processes were skipped):")
        for kind, name in UNSUPPORTED_PROCESSES:
            print(f"  - [{kind}] {name}")
        print("=" * 70)


if __name__ == "__main__":
    main()
'''


def _py_repr(v):
    """Repr that JSON-friendly-ifies floats and None."""
    if isinstance(v, float):
        if v != v:  # NaN
            return "float('nan')"
        if v == float("inf"):
            return "float('inf')"
        if v == float("-inf"):
            return "float('-inf')"
    return repr(v)


def _col_meta_for_column(col):
    """Pluck the JSON-serialisable metadata for a column object."""
    meta = {
        "name": col.get("name"),
        "type": col.get("type", "number"),
        "data": col.get("data"),
        "compression": col.get("compression"),
        "timeFormat": col.get("timeFormat"),
        "binWidth": col.get("binWidth", 1.0),
        "refId": col.get("refId"),
        "processes": [
            {
                "funcname": p.get("funcname"),
                "name": p.get("name"),
                "args": p.get("args", {}),
            }
            for p in col.get("processes", [])
        ],
    }
    return {k: v for k, v in meta.items() if v is not None or k in ("processes",)}


def emit(session_path: Path, output_path: Path) -> None:
    with open(session_path) as f:
        session = json.load(f)

    runtime_src = RUNTIME_PATH.read_text()
    # Strip the runtime's own imports — we add them in HEADER — and dedent
    runtime_lines = []
    for line in runtime_src.splitlines():
        if line.startswith("from __future__") or line.startswith("import ") \
                or line.startswith("from "):
            # keep typing imports; drop numpy/pandas/scipy since HEADER has them
            if "numpy" in line or "pandas" in line or "scipy" in line \
                    or line.startswith("from __future__"):
                continue
        runtime_lines.append(line)
    runtime_block = "\n".join(runtime_lines)

    raw_data = session.get("rawData", {})
    columns = session.get("data", [])
    # Analyses are free table-process nodes under `tableProcesses` (the `tables`
    # grouping was removed 2026-06-15). Legacy sessions that still carry grouped
    # `tables` are flattened in for back-compat.
    table_processes = session.get("tableProcesses", [])
    legacy_tables = session.get("tables", [])
    plots = session.get("plots", [])
    stored_values = session.get("storedValues", {}) or {}

    # Build column metadata dict
    col_meta = {}
    for c in columns:
        cid = c.get("id")
        if cid is None:
            continue
        col_meta[cid] = _col_meta_for_column(c)

    # Each table process keeps its registry name (AnCiR uses `name`, e.g.
    # 'Cosinor', 'GroupComparison'); the runtime maps name → tp-key. Flatten the
    # free `tableProcesses` plus any legacy grouped `tables` into one ordered list.
    tps_clean = [
        {"name": tp.get("name"), "args": tp.get("args", {})}
        for tp in table_processes
    ]
    for t in legacy_tables:
        for p in t.get("processes", []):
            tps_clean.append({"name": p.get("name"), "args": p.get("args", {})})

    # Embed as JSON strings parsed at startup so null/true/false stay valid.
    # Convert string keys back to int for COLUMN_META so column ids match.
    parts = [HEADER, "", runtime_block, ""]
    parts.append("# ----- Session data (embedded) -----")
    parts.append(f"RAW_DATA = json.loads({json.dumps(json.dumps(raw_data))})")
    parts.append("RAW_DATA = {int(k) if k.lstrip('-').isdigit() else k: v "
                 "for k, v in RAW_DATA.items()}")
    parts.append(f"_COL_META_RAW = json.loads({json.dumps(json.dumps(col_meta))})")
    parts.append("COLUMN_META = {int(k): v for k, v in _COL_META_RAW.items()}")
    parts.append(f"TABLE_PROCESSES = json.loads({json.dumps(json.dumps(tps_clean))})")
    parts.append(f"PLOTS = json.loads({json.dumps(json.dumps(plots))})")
    parts.append(f"STORED_VALUES = json.loads({json.dumps(json.dumps(stored_values))})")
    parts.append(FOOTER_RUN)

    output_path.write_text("\n".join(parts))
    print(f"[ancir-emit] wrote {output_path} "
          f"({len(columns)} columns, {len(tps_clean)} table processes)")


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("session", type=Path, help="AnCiR session.json")
    p.add_argument("-o", "--output", type=Path, default=Path("analysis.py"),
                   help="output Python script (default: analysis.py)")
    args = p.parse_args(argv)
    if not args.session.exists():
        print(f"error: {args.session} not found", file=sys.stderr)
        return 2
    emit(args.session, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
