// gen-schema.js — regenerate the normalizer's node schema FROM THE LIVE REGISTRY.
//
//   vite-node src/emit/gen-schema.js
//
// Writes src/emit/session-schema.generated.json: for every table process, the
// structural facts the normalizer needs, read from the source of truth so they can't
// drift:
//   - inputs   : {scalar, array} column-id fields (which args are column references)
//   - params   : default parameter values (to fill omitted params)
//   - fixedOut : the node's fixed output keys, taken verbatim from its `out` template
//                (this is what a hand-authored schema gets wrong — e.g. Cosinor's
//                `cosinorx` was missed, silently breaking the fit; ADR 2026-07-15)
//   - perYPrefix : the per-Y output-key prefix (entry.yOutKeyPrefix), or null — the
//                  normalizer expands it to `${prefix}${yid}` for each selected Y
//
// Semantic validators and generator baking stay in code (schema.js) — they are logic,
// not registry facts. Run this whenever the AnCiR node registry changes.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ensureDom } from '../engine/bootstrapDom.js';

await ensureDom();
const { ensureRegistry } = await import('../engine/session.js');
await ensureRegistry();
const { appConsts } = await import('$lib/core/core.svelte.js');

// Arg keys that are wiring/bookkeeping, never user-facing params (mirrors the engine's
// describeCapabilities()). Input-column fields are also excluded from params below.
const STRUCTURAL = new Set([
	'out',
	'valid',
	'forcollected',
	'collectedType',
	'preProcesses',
	'tableProcesses',
	'outColIds',
	'storedValueRefs',
	'aggregates'
]);

const unwrap = (v) => (v && typeof v === 'object' && 'val' in v ? v.val : v);

// Nodes whose per-Y output keys are NOT a simple `${prefix}${yid}` — they come from the
// engine's synthesizeDynamicOut() (method/segment/category-dependent, e.g. `${yid}_period`
// for RhythmicityAnalysis, per-segment for Split, per-category for LongToWide). Their
// `yOutKeyPrefix` is the collected-mode prefix, which does NOT match the standalone keys,
// so emitting it would create a broken session. Mark them 'runtime' and let the normalizer
// skip dynamic pre-allocation (with a warning) until a code-side rule is ported. Keep this
// list in sync with the switch in src/engine/session.js:synthesizeDynamicOut().
const RUNTIME_DYNAMIC = new Set([
	'RhythmicityAnalysis',
	'MovingAnalysis',
	'Split',
	'CollectColumns',
	'StoredValueGroup',
	'Duplicate',
	'LongToWide'
]);

const schema = {};
for (const [name, entry] of appConsts.tableProcessMap ?? new Map()) {
	const cif = entry.columnIdFields ?? {};
	const scalar = cif.scalar ?? [];
	const array = cif.array ?? [];
	const inputFields = new Set([...scalar, ...array]);

	const params = {};
	for (const [k, v] of entry.defaults ?? new Map()) {
		if (STRUCTURAL.has(k) || inputFields.has(k)) continue;
		params[k] = unwrap(v);
	}

	// Fixed output keys come straight from the `out` template — the authoritative list.
	const outTemplate = entry.defaults?.get?.('out');
	const fixedOut = outTemplate ? Object.keys(outTemplate) : [];

	const complex = RUNTIME_DYNAMIC.has(name);
	// dynamicKind: 'fixed' (no per-Y outputs), 'prefix' (per-Y ${prefix}${yid} — safe to
	// pre-allocate), or 'runtime' (keys depend on data/method — not statically knowable).
	const dynamicKind = complex ? 'runtime' : entry.yOutKeyPrefix ? 'prefix' : 'fixed';

	schema[name] = {
		displayName: entry.displayName ?? name,
		family: entry.family ?? 'Other',
		inputs: { scalar, array },
		params,
		fixedOut,
		dynamicKind,
		// Per-Y prefix for dynamicKind==='prefix' (e.g. cosinory_, binnedy_); null otherwise.
		perYPrefix: dynamicKind === 'prefix' ? entry.yOutKeyPrefix : null
	};
}

const out = {
	_comment:
		'AUTO-GENERATED by src/emit/gen-schema.js from the AnCiR registry. Do not hand-edit. ' +
		'Consumed by src/emit/schema.js (which adds code-side validators + generators).',
	generatedFromVersion: appConsts.version ?? 'unknown',
	count: Object.keys(schema).length,
	nodes: schema
};

const target = fileURLToPath(new URL('./session-schema.generated.json', import.meta.url));
writeFileSync(target, JSON.stringify(out, null, '\t') + '\n');
console.log(`Wrote ${out.count} node schemas → ${target}`);
// Spot-check the node that motivated this: Cosinor MUST carry cosinorx in fixedOut.
const cos = schema.Cosinor;
if (cos) {
	console.log(
		`Cosinor: fixedOut=[${cos.fixedOut.join(', ')}] perYPrefix=${cos.perYPrefix}`
	);
	if (!cos.fixedOut.includes('cosinorx'))
		console.warn('WARNING: Cosinor.fixedOut is missing cosinorx — the fit will not compute!');
}
